FORMAT: 1A
HOST: https://globalgas.com

# Global Gas - C2 Librerias

## GLOBALNET [/globalnet]

### DESCARGAR_EMPLEADOS [POST]

#### Acciones

- e_RESPONSE = CURL
    - URL: ???
    - CONNECTTIMEOUT: 10
    - TIMEOUT: 60
    - HTTPHEADER: ???
    - CUSTOMREQUEST: POST
    - POSTFIELDS:
        - ???
    - RETURNTRANSFER: 1
- m_RESPONSE = json_decode(e_RESPONSE, true)
- e_HTTP_CODE = curl_get_info(CURLINFO_HTTP_CODE)
- SWITCH e_HTTP_CODE
    - CASE ???
        - THROW

#### Retorno

- m_RESPONSE
    - []
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - NOMBRE
        - NUMERO
        - TELEFONO
        - IMAGEN

#### Excepciones

- ???

### DESCARGAR_UNIDADES [POST]

#### Acciones

- e_RESPONSE = CURL
    - URL: ???
    - CONNECTTIMEOUT: 10
    - TIMEOUT: 60
    - HTTPHEADER: ???
    - CUSTOMREQUEST: POST
    - POSTFIELDS:
        - ???
    - RETURNTRANSFER: 1
- m_RESPONSE = json_decode(e_RESPONSE, true)
- e_HTTP_CODE = curl_get_info(CURLINFO_HTTP_CODE)
- SWITCH e_HTTP_CODE
    - CASE ???
        - THROW

#### Retorno

- m_RESPONSE
    - []
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - NUMERO ECONOMICO
        - ID_CHOFER
        - ID_AYUDANTE
        - ID_AYUDANTE_2
        - ID_RUTA
        - TIPO_UNIDAD
        - CUENTALITROS
        - ROTOGAUGE
        - DOTACION
            - CANTIDAD_10
            - CANTIDAD_20
            - CANTIDAD_30
            - CANTIDAD_45

#### Excepciones

- ???

### DESCARGAR_SINCRONIZACION [POST]

#### Acciones

- m_CONFIGURACION.EMPLEADOS_FECHA_ULTIMA_ACTUALIZACION = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='EMPLEADOS_FECHA_ULTIMA_ACTUALIZACION'
- m_CONFIGURACION.EMPLEADOS_ULTIMO_ID_INSERTADO = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='EMPLEADOS_ULTIMO_ID_INSERTADO'
- m_CONFIGURACION.UNIDADES_FECHA_ULTIMA_ACTUALIZACION = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='UNIDADES_FECHA_ULTIMA_ACTUALIZACION'
- m_CONFIGURACION.UNIDADES_ULTIMO_ID_INSERTADO = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='UNIDADES_ULTIMO_ID_INSERTADO'
- m_CONFIGURACION.PRECIOS_FECHA_ULTIMA_ACTUALIZACION = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='PRECIOS_FECHA_ULTIMA_ACTUALIZACION'
- m_CONFIGURACION.PRECIOS_ULTIMO_ID_INSERTADO = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='PRECIOS_ULTIMO_ID_INSERTADO'
- m_CONFIGURACION.SERVICIOS_FECHA_ULTIMA_ACTUALIZACION = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='SERVICIOS_FECHA_ULTIMA_ACTUALIZACION'
- m_CONFIGURACION.SERVICIOS_ULTIMO_ID_INSERTADO = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='SERVICIOS_ULTIMO_ID_INSERTADO'
- m_CONFIGURACION.CUENTAS_OCULTAS_ULTIMO_ID_INSERTADO = QUERY - SELECT GEN_VALOR FROM conf_general WHERE GEN_PARAMETRO='CUENTAS_OCULTAS_ULTIMO_ID_INSERTADO'
- e_RESPONSE = CURL
    - URL: ???
    - CONNECTTIMEOUT: 10
    - TIMEOUT: 60
    - HTTPHEADER: ???
    - CUSTOMREQUEST: POST
    - POSTFIELDS:
        - CONFIGURACION: m_CONFIGURACION
        - ???
    - RETURNTRANSFER: 1
- m_RESPONSE = json_decode(e_RESPONSE, true)
- e_HTTP_CODE = curl_get_info(CURLINFO_HTTP_CODE)
- SWITCH e_HTTP_CODE
    - CASE ???
        - THROW

#### Retorno

- m_RESPONSE
    - []
        - TIPO: 'EMPLEADOS.AGREGAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - NOMBRE
        - NUMERO
        - TELEFONO
        - IMAGEN
    - []
        - TIPO: 'EMPLEADOS.ACTUALIZAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - NOMBRE
        - NUMERO
        - TELEFONO
        - IMAGEN
    - []
        - TIPO: 'UNIDADES.AGREGAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - NUMERO_ECONOMICO
        - ID_CHOFER
        - ID_AYUDANTE
        - ID_AYUDANTE_2
        - ID_RUTA
        - TIPO_UNIDAD
        - CUENTALITROS
        - ROTOGAUGE
        - DOTACION
            - CANTIDAD_10
            - CANTIDAD_20
            - CANTIDAD_30
            - CANTIDAD_45
    - []
        - TIPO: 'UNIDADES.ACTUALIZAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - NUMERO_ECONOMICO
        - ID_CHOFER
        - ID_AYUDANTE
        - ID_AYUDANTE_2
        - ID_RUTA
        - TIPO_UNIDAD
        - CUENTALITROS
        - ROTOGAUGE
        - DOTACION
            - CANTIDAD_10
            - CANTIDAD_20
            - CANTIDAD_30
            - CANTIDAD_45
    - []
        - TIPO: 'PRECIOS.AGREGAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - INDICE
        - PRODUCTO
        - ANIO
        - MES
        - PRECIO_NETO
    - []
        - TIPO: 'PRECIOS.ACTUALIZAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - INDICE
        - PRODUCTO
        - ANIO
        - MES
        - PRECIO_NETO
    - []
        - TIPO: 'SERVICIOS.AGREGAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - CLIENTE
        - CUENTA
        - CUENTA_OCULTA
        - ID_GLOBALNET_UNIDAD
        - TIPO_SERVICIO
        - FECHA_PROGRAMADO
        - ESTATUS
        - DOMICILIO
        - INDICE
        - DESCUENTO
        - APLICA_CREDITO
    - []
        - TIPO: 'SERVICIOS.ACTUALIZAR'
        - ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION
        - CLIENTE
        - CUENTA
        - CUENTA_OCULTA
        - ID_GLOBALNET_UNIDAD
        - TIPO_SERVICIO
        - FECHA_PROGRAMADO
        - ESTATUS
        - DOMICILIO
        - INDICE
        - DESCUENTO
        - APLICA_CREDITO
    - []
        - TIPO: 'CUENTAS_OCULTAS.AGREGAR'
        - ID_GLOBALNET
        - CUENTA_OCULTA
        - FECHAHORA
        - ID_GLOBALNET_UNIDAD
        - ESTATUS

#### Excepciones

- ???

## EMPLEADO [/empleado]

#### Atributos

- ID
- ID_GLOBALNET
- FECHA_ULTIMA_MODIFICACION
- NOMBRE
- NUMERO
- TELEFONO
- PERFIL
- CONTRASENA
- APIKEY

### CONSTRUCTOR [POST]

#### Acciones

- IF a_EMPLEADO = QUERY - SELECT EMP_ID, EMP_ID_GLOBALNET, EMP_FECHA_ULTIMA_MODIFICACION, EMP_NOMBRE, EMP_NUMERO, EMP_TELEFONO, EMP_ACC_PERFIL, EMP_ACC_CONTRASENA, EMP_ACC_APIKEY FROM cat_empleados LEFT JOIN cat_empleados_accesos ON EMP_NUMERO=EMP_ACC_NUMERO WHRE EMP_NUMERO='PARAM.NUMERO'
    - THIS.ID = a_EMPLEADO.EMP_ID
    - THIS.ID_GLOBALNET = a_EMPLEADO.EMP_ID_GLOBALNET
    - THIS.FECHA_ULTIMA_MODIFICACION = a_EMPLEADO.EMP_FECHA_ULTIMA_MODIFICACION
    - THIS.NOMBRE = a_EMPLEADO.EMP_NOMBRE
    - THIS.NUMERO = a_EMPLEADO.EMP_NUMERO
    - THIS.TELEFONO = a_EMPLEADO.EMP_TELEFONO
    - THIS.PERFIL = a_EMPLEADO.EMP_ACC_PERFIL
    - THIS.CONTRASENA = a_EMPLEADO.EMP_ACC_CONTRASENA
    - THIS.APIKEY = a_EMPLEADO.EMP_ACC_APIKEY
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.CONSTRUCTOR.NUMERO_INEXISTENTE El numero de empleado especificado no existe

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.CONSTRUCTOR.NUMERO_INEXISTENTE

+ Atributos
    - NUMERO

### VALIDAR_CONTRASENA [POST]

#### Acciones

- IF THIS.CONTRASENA != MULTHEX(PARAM.CONTRASENA) && THIS.CONTRASENA != MD5(PARAM.CONTRASENA)
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_CONTRASENA.CONTRASENA_INCORRECTA La contraseña es incorrecta

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_CONTRASENA.CONTRASENA_INCORRECTA

+ Attributes
    - CONTRASENA

### VALIDAR_APIKEY [POST]

#### Acciones

- IF THIS.APIKEY != PARAM.APIKEY
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_APILEY.APIKEY_INCORRECTO El apikey es incorrecto

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_APILEY.APIKEY_INCORRECTO

+ Attributes
    - CONTRASENA

### VALIDAR_SUPERVISOR [POST]

#### Acciones

- IF THIS.PERFIL != 'SUPERVISOR'
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR El usuario no tiene el perfil de supervisor

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR

## UNIDAD [/unidad]

#### Atributos

- ID
- ID_GLOBALNET
- FECHA_ULTIMA_MODIFICACION
- ID_CHOFER
- ID_AYUDANTE
- ID_AYUDANTE_2
- ID_RUTA
- TIPO_UNIDAD
- DOTACION

### CONSTRUCTOR [POST]

#### Acciones

- IF a_UNIDAD = QUERY - SELECT UNI_ID, UNI_ID_GLOBALNET, UNI_FECHA_ULTIMA_MODIFICACION, UNI_ID_CHOFER, UNI_ID_AYUDANTE, UNI_ID_AYUDANTE_2, UNI_ID_RUTA, UNI_TIPO_UNIDAD, UNI_CUENTALIGROS, UNI_ROTOGAUGE, UNI_DOTACION FROM cat_unidades WHRE UNI_ID_GLOBALNET='PARAM.ID_GLOBALNET'
    - THIS.ID = a_UNIDAD.UNI_ID
    - THIS.ID_GLOBALNET = a_UNIDAD.UNI_ID_GLOBALNET
    - THIS.FECHA_ULTIMA_MODIFICACION = a_UNIDAD.UNI_FECHA_ULTIMA_MODIFICACION
    - THIS.ID_CHOFER = a_UNIDAD.UNI_ID_CHOFER
    - THIS.ID_AYUDANTE = a_UNIDAD.UNI_ID_AYUDANTE
    - THIS.ID_AYUDANTE_2 = a_UNIDAD.UNI_ID_AYUDANTE_2
    - THIS.ID_RUTA = a_UNIDAD.UNI_ID_RUTA
    - THIS.TIPO_UNIDAD = a_UNIDAD.UNI_TIPO_UNIDAD
    - THIS.CUENTALITROS = a_UNIDAD.UNI_CUENTALITROS
    - THIS.ROTOGAUGE = a_UNIDAD.UNI_ROTOGAUGE
    - THIS.DOTACION = json_decode(a_UNIDAD.UNI_DOTACION, TRUE)
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE La unidad especificada no existe

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE

+ Atributos
    - ID_GLOBALNET

### VALIDAR_PROPIETARIO [POST]

#### Acciones

- IF THIS.ID_GLOBALNET_UNIDAD != $GLOBALS['SYSTEM']['SECURITY']['UNIDAD'].ID_GLOBALNET_UNIDAD
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.VALIDAR_PROPIETARIO.NO_PROPIETARIO El usuario no esta asignado a la unidad

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.VALIDAR_PROPIETARIO.NO_PROPIETARIO

## SERVICIO [/servicio]

#### Atributos

- ID
- ID_GLOBALNET
- FECHA_ULTIMA_MODIFICACION
- CLIENTE
- CUENTA
- CUENTA_OCULTA
- ID_GLOBALNET_UNIDAD
- TIPO_SERVICIO
- FECHA_PROGRAMADO
- ESTATUS
- DOMICILIO

### CONSTRUCTOR [POST]

#### Acciones

- IF a_SERVICIO = QUERY - SELECT SER_ID, SER_ID_GLOBALNET, SER_FECHA_ULTIMA_MODIFICACION, SER_CLIENTE, SER_CUENTA, SER_CUENTA_OCULTA, SER_ID_GLOBALNET_UNIDAD, SER_TIPO_SERVICIO, SER_FECHA_PROGRAMADO, SER_ESTATUS, SER_DOMICILIO FROM dat_servicios WHRE SER_ID_GLOBALNET='PARAM.ID_GLOBALNET'
    - THIS.ID = a_SERVICIO.SER_ID
    - THIS.ID_GLOBALNET = a_SERVICIO.SER_ID_GLOBALNET
    - THIS.FECHA_ULTIMA_MODIFICACION = a_SERVICIO.SER_FECHA_ULTIMA_MODIFICACION
    - THIS.CLIENTE = a_SERVICIO.SER_CLIENTE
    - THIS.CUENTA = a_SERVICIO.SER_CUENTA
    - THIS.CUENTA_OCULTA = a_SERVICIO.SER_CUENTA_OCULTA
    - THIS.ID_GLOBALNET_UNIDAD = a_SERVICIO.SER_ID_GLOBALNET_UNIDAD
    - THIS.TIPO_SERVICIO = a_SERVICIO.SER_TIPO_SERVICIO
    - THIS.FECHA_PROGRAMADO = a_SERVICIO.SER_FECHA_PROGRAMADO
    - THIS.ESTATUS = a_SERVICIO.SER_ESTATUS
    - THIS.DOMICILIO = json_decode(a_SERVICIO.SER_DOMICILIO, TRUE)
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.CONSTRUCTOR.SERVICIO_INEXISTENTE El servicio especificado no existe

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.CONSTRUCTOR.SERVICIO_INEXISTENTE

+ Atributos
    - ID_GLOBALNET

### VALIDAR_PROPIETARIO [POST]

#### Acciones

- IF THIS.ID_GLOBALNET_UNIDAD != $GLOBALS['SYSTEM']['SECURITY']['UNIDAD'].ID_GLOBALNET_UNIDAD
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.VALIDAR_PROPIETARIO.NO_PROPIETARIO El usuario no esta asignado a la unidad a la que pertenece el servicio

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.VALIDAR_PROPIETARIO.NO_PROPIETARIO

### VALIDAR_CLIENTE [POST]

#### Acciones

- IF THIS.CLIENTE != PARAM.CLIENTE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.VALIDAR_CLIENTE.CLIENTE_INCORRECTO El cliente especificado no corresponde al servicio

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.VALIDAR_CLIENTE.CLIENTE_INCORRECTO

+ Atributos
    - CLIENTE

### VALIDAR_CUENTA [POST]

#### Acciones

- IF THIS.CUENTA != PARAM.CUENTA
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.VALIDAR_CUENTA.CUENTA_INCORRECTA La cuenta especificada no corresponde al servicio

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.SERVICIO.VALIDAR_CUENTA.CUENTA_INCORRECTA

+ Atributos
    - CUENTA

## CUENTA_OCULTA [/cuenta_oculta]

#### Atributos

- ID
- ID_GLOBALNET
- FECHAHORA
- ID_GLOBALNET_UNIDAD
- ESTATUS

### CONSTRUCTOR [POST]

#### Acciones

- IF a_CUENTA_OCULTA = QUERY - SELECT CUE_OCU_ID, CUE_OCU_ID_GLOBALNET, CUE_OCU_FECHAHORA, CUE_OCU_ID_GLOBALNET_UNIDAD, CUE_OCU_ESTATUS FROM dat_cuentas_ocultas WHRE CUE_OCU_ID_GLOBALNET='PARAM.ID_GLOBALNET'
    - THIS.ID = a_CUENTA_OCULTA.CUE_OCU_ID
    - THIS.ID_GLOBALNET = a_CUENTA_OCULTA.CUE_OCU_ID_GLOBALNET
    - THIS.FECHAHORA = a_CUENTA_OCULTA.CUE_OCU_FECHAHORA
    - THIS.ID_GLOBALNET_UNIDAD = a_CUENTA_OCULTA.CUE_OCU_ID_GLOBALNET_UNIDAD
    - THIS.ESTATUS = a_CUENTA_OCULTA.CUE_OCU_ESTATUS
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.CUENTA_OCULTA.CONSTRUCTOR.CUENTA_OCULTA_INEXISTENTE La cuenta oculta especificada no existe

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CUENTA_OCULTA.CONSTRUCTOR.CUENTA_OCULTA_INEXISTENTE

+ Atributos
    - ID_GLOBALNET

### VALIDAR_PROPIETARIO [POST]

#### Acciones

- IF THIS.ID_GLOBALNET_UNIDAD != $GLOBALS['SYSTEM']['SECURITY']['UNIDAD'].ID_GLOBALNET_UNIDAD
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.CUENTA_OCULTA.VALIDAR_PROPIETARIO.NO_PROPIETARIO El usuario no esta asignado a la unidad a la que pertenece la cuenta oculta

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CUENTA_OCULTA.VALIDAR_PROPIETARIO.NO_PROPIETARIO

### VALIDAR_DISPONIBLE [POST]

#### Acciones

- IF THIS.ESTATUS == 1
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.CUENTA_OCULTA.VALIDAR_DISPONIBLE.NO_DISPONIBLE La cuenta oculta no esta disponible

#### Retorno

- N/A

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CUENTA_OCULTA.VALIDAR_DISPONIBLE.NO_DISPONIBLE


## CLIENTES [/clientes]

#### Attribute

- ID
- ID_GLOBALNET
- FECHAHORA
- TELEFONO
- DOMICILIO
- NUMERO

### CONSTRUCTOR [POST]

#### Acciones

- IF a_CLIENTES = QUERY - SELECT CLI_ID, CLI_ID_GLOBALNET, CLI_FECHA_ULTIMA_MODIFICACION AS FECHA_ULTIMA_MODIFICACION, CLI_TELEFONO AS TELEFONO, CLI_DOMICILIO AS DOMICILIO, CLI_NUMERO AS NUMERO FROM cat_clientes WHERE CLI_GLOBALNET_ID='PARAM.ID_GLOBALNET'
    - THIS.ID = a_CLIENTES.CLI_ID
    - THIS.ID_GLOBALNET = a_CLIENTES.CLI_ID_GLOBALNET
    - THIS.FECHA_ULTIMA_MODIFICACION = a_CLIENTES.FECHA_ULTIMA_MODIFICACION
    - THIS.TELEFONO = a_CLIENTES.TELEFONO
    - THIS.DOMICILIO = a_CLIENTES.DOMICILIO
    - THIS.NUMERO = a_CLIENTES.NUMERO
- ELSE IF a_CLIENTES = QUERY - SELECT CLI_ID, CLI_ID_GLOBALNET, CLI_FECHA_ULTIMA_MODIFICACION AS FECHA_ULTIMA_MODIFICACION, CLI_TELEFONO AS TELEFONO, CLI_DOMICILIO AS DOMICILIO, CLI_NUMERO AS NUMERO FROM cat_clientes WHERE CLI_NUMERO = 'PARAM.ID_GLOBALNET' AND CLI_TELEFONO = 'PARAM.TELEFONO'
    - THIS.ID = a_CLIENTES.CLI_ID
    - THIS.ID_GLOBALNET = a_CLIENTES.CLI_ID_GLOBALNET
    - THIS.FECHA_ULTIMA_MODIFICACION = a_CLIENTES.FECHA_ULTIMA_MODIFICACION
    - THIS.TELEFONO = a_CLIENTES.TELEFONO
    - THIS.DOMICILIO = a_CLIENTES.DOMICILIO
    - THIS.NUMERO = a_CLIENTES.NUMERO
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.CONSTRUCTOR.CLIENTE_INEXISTENTE La cliente especificada no existe

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.CONSTRUCTOR.CLIENTE_INEXISTENTE

+ Atributos
    - TELEFONO
    - ID_GLOBALNET
    - NUMERO

### VALIDAR_APIKEY[POST]    

#### Acciones

- IF e_APIKEY = QUERY - SELECT CLI_ACC_APIKEY  AS KEY FROM cat_clientes_accesos WHERE CLI_ACC_TELEFONO = THIS.TELEFONO
    - CLI_ACC_TELEFONO : THIS.TELEFONO
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.VALIDAR_APIKEY.APIKEY_INVALIDO El apikey invalido

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.VALIDAR_APIKEY.APIKEY_INVALIDO

+ Atributos
    - TELEFONO

### VALIDAR_SESION[POST]    

#### Acciones

- IF e_SES_ID = QUERY - SELECT SES_ID FROM seg_sesiones WHERE SES_EMPLEADO = THIS.ID AND SES_SESION = THIS.SESION 
    - SES_EMPLEADO : THIS.ID
    - SES_SESION : PARAM.SESION

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.VALIDAR_SESION.SESION_EXPIRADA

+ Atributos
    - TELEFONO    

### VALIDAR_PROPIETARIO[POST]    

#### Acciones

- IF e_CUENTA = QUERY - SELECT CUE_ID  FROM cat_cuentas WHERE CUE_CLIENTE = THIS.ID_GLOBALNET AND CUE_ID = PARAM.CUENTA
    - CUE_CLIENTE : THIS.ID_GLOBALNET
    - CUE_ID : PARAM.CUENTA
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.VALIDAR_PROPIETARIO.CUENTA_IMPROPIA La cuenta de impropia

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.VALIDAR_PROPIETARIO.CUENTA_IMPROPIA

+ Atributos
    - CUENTA


## CUENTAS [/clientes]

#### Attribute

- ID
- ID_GLOBALNET
- FECHA_ULTIMA_MODIFICACION
- TIPO_SERVICIO
- DOMICILIO
- NUMERO
- CICLO
- COORDENADAS

### CONSTRUCTOR [POST]

#### Acciones

- IF a_CUENTAS = QUERY - SELECT CUE_ID, CUE_ID_GLOBALNET, CUE_NOMBRE, CUE_TIPO_SERVICIO, CUE_NUMERO, CUE_FECHA_ULTIMA_MODIFICACION, CUE_COORDENADAS, CUE_CICLO WHERE CLI_ID_GLOBALNET = 'PARAM.ID_GLOBALNET'
    - THIS.ID = a_CUENTAS.CUE_ID
    - THIS.ID_GLOBALNET = a_CUENTAS.CUE_ID_GLOBALNET
    - THIS.NOMBRE = a_CUENTA.NOMBRE
    - THIS.TIPO_SERVICIO = a_CUENTA.TIPO_SERVICIO
    - THIS.NUMERO = a_CUENTA.NUMERO
    - THIS.FECHA_ULTIMA_MODIFICACION = a_CUENTA.FECHA_ULTIMA_MODIFICACION
    - THIS.COORDENADA = a_CUENTA.CUE_COORDENADAS
    - THIS.CICLO = a_CUENTA.CUE_CICLO
- ELSE
    - THROW GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.CONSTRUCTOR.CLIENTE_INEXISTENTE La cliente especificada no existe

#### Excepciones

- GLOBAL_GAS.BE:C2.LIBRARY.CLIENTE.CONSTRUCTOR.CLIENTE_INEXISTENTE

+ Atributos
    - TELEFONO
    - ID_GLOBALNET
    - NUMERO