FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Cliente Global Gas - C2

## CAT.CLIENTES [/cat.clientes]

### REPLICAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C2.LIBRARY.GLOBALNET

#### Acciones

- IF m_CLIENTE = GLOBAL_GAS.BE:C2.LIBRARY.GLOBALNET.DESCARGAR_CLIENTE ()
    - GLOBAL_GAS.BE:C3.STEP.CAT.CLIENTES.ELIMINAR_TODOS ( )
    - FOREACH m_CLIENTE AS m_UN_CLIENTE
        - GLOBAL_GS.BE:C3.STEP.CAT.CLIENTES.AGREGAR ( ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, NOMBRE, APELLIDO_PATERNO, ID_CLIENTE, NOMBRE, NUMERO, TELEFONO, DOMICILIO )
            - ID_GLOBALNET : m_UN_CLIENTE.ID_GLOBALNET,
            - FECHA_ULTIMA_MODIFICACION : m_UN_CLIENTE.FECHA_ULTIMA_MODIFICACION
            - NOMBRE : m_UN_CLIENTE.NOMBRE
            - APELLIDO_PATERNO : m_UN_CLIENTE.APELLIDO_PATERNO
            - ID_CLIENTE : m_UN_CLIENTE.ID_CLIENTE
            - NUMERO : m_UN_CLIENTE.NUMERO
            - TELEFONO : m_UN_CLIENTE.TELEFONO
            - DOMICLIO : m_UN_CLIENTE.DOMICILIO

#### Retorno

- N/A

### GENERAR_CODIGO [POST]

#### Acciones

- IF QUERY - SELECT ID_CLIENTE FROM cat_clientes WHERE TELEFONO = PARAM.TELEFONO AND NOMBRE != APP
    - TROW 402-01
- ELSE
    - GLOBAL_GAS.BE:C3.STEP.CAT.CLIENTES.GENERAR_CODIGO ( TELEFONO )
        - TELEFONO : PARAM.TELEFONO

#### Retorno

- APIKEY

+ Attribute
    - TELEFONO

### INICIAR_SESION [POST]

#### Libreria

- GLOBAL_GAS.BE:C2.LIBRARY.CLIENTES

#### Acciones

- TRY
    - o_CLIENTE = NEW CLIENTE ( TELEFONO, NUMERO_CUENTA )
        - TELEFONO : PARAM.TELEFONO
        - NUMERO_CUENTA : PARAM.NUMERO_CUENTA
    - o_CLIENTE.VALIDAR_APIKEY( APIKEY )
        - APIKEY : PARAM.APIKEY  
    - e_JWT = GLOBAL_GAS.B3:C3.STEP.CAT.CLIENTES.OBTENER_JWT ( CLIENTE.ID_CLIENTE )
- CATCH
    - RETROW

- RETURN e_JWT

#### Retorno

- e_JWT

+ Attribute
    - TELEFONO
    - NUMERO_CUENTA

### VALIDAR_CODIGO[POST]    
    
#### Acciones

- TRY
    - e_JWT = GLOBAL_GAS.B3:C3.STEP.CAT.CLIENTES.VALIDAR_CODIGO ( TELEFONO, CODIGO, APIKEY )
        - TELEFONO : PARAM.TELEFONO
        - CODIGO : PARAM.CODIGO
        - APIKEY : PARAM.APIKEY
- CATCH
    - RETROW
- IF ( e_JWT != TRUE ) 
    RETURN STATUS
        - REGISTRO : FALSE
        - e_JWT
- ELSE
    RETURN STATUS
        - REGISTRO = TRUE

#### Retorno

- m_STATUS
    - REGISTRO : TRUE / FALSE
    - e_JWT : 'iksbcjsbdjvcbjsdbcbsubvihvsdb'

+ Attribute
    - TELEFONO
    - CODIGO   

### AGREGAR[POST]

#### Acciones 

- TRY
    - e_CLIENTE_ID = GLOBAL_GAS.BE:C3.STEP.CAT.CLIENTES.AGREGAR ( NOMBRE, TELEFONO, DOMICILIO )
        - NOMBRE : PARAM.NOMBRE
        - TELEFONO : PARAM.TELEFONO
        - DOMICLIO : PARAM.DOMICILIO
    - e_JWT = GLOBAL_GAS.BE:C3.STEP.CAT.CUENTAS.AGREGAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO )
        - DOMICILIO : PARAM.DOMICILIO
        - TIPO_SERVICIO : PARAM.TIPO_SERVICIO
        - TELEFONO : PARAM.TELEFONO
        - CLIENTE : e_CLIENTE_ID
        - CICLO : PARAM.CICLO
- CATCH
    RETROW

#### Retorno

- e_JWT

+ Attribute
    - NOMBRE
    - TELEFONO
    - DOMICLIO
    - TIPO_SERVICIO
    - CLIENTE
    - CICLO

## CAT.CLIENTES.ACCESOS

### OBTENER.APIKEY [POST]

#### Acciones

- TRY
    - IF QUERY - SELECT ID_CLIENTE FROM cat_clientes WHERE TELEFONO = PARAM.TELEFONO AND NOMBRE != APP
        - TROW 402-01
    - ELSE
        - e_APIKEY = GLOBAL_GAS.BE:C3.STEP.CAT.CLIENTES_ACCESOS.GENERAR_APIKEY ( TELEFONO )
            - TELEFONO : PARAM.TELEFONO
- CATCH
    - RETROW

#### Retorno

- e_APIKEY

+ Attribute
    - TELEFONO

## CAT.CUENTAS [/cat.cuentas]    

### AGREGAR[POST]

#### Acciones

- TRY
    - o_CLIENTE = NEW CLIENTE ( ID_CLIENTE )
    - o_CLIENTE.VALIDAR_SESION
    - IF ( o_CLIENTE.IS_EDITABLE() )
        - GLOBAL_GAS.BE:C3.STEP.CAT_CUENTAS.AGREGAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, ID_CLIENTE, CICLO )
    - ELSE
        - RETROW  
- CATCH
    RETROW

#### Retorno

- N/A

+ Attribute
    - NOMBRE
    - TELEFONO
    - DOMICLIO
    - TIPO_SERVICIO
    - ID_CLIENTE
    - CICLO

### ACTUALIZAR[POST]

#### Acciones

- TRY
    - o_CLIENTE = NEW CLIENTE ( ID_CLIENTE )
    - o_CLIENTE.VALIDAR_SESION
    - IF ( o_CLIENTE.IS_EDITABLE() )
        - GLOBAL_GAS.BE:C3.STEP.CAT_CUENTAS.ACTUALIZAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, ID_CLIENTE, CICLO, ID_CUENTAS )
    - ELSE
        - RETROW  
- CATCH
    RETROW

#### Retorno

- N/A

+ Attribute
    - NOMBRE
    - TELEFONO
    - DOMICLIO
    - TIPO_SERVICIO
    - ID_CLIENTE
    - CICLO
    - ID_CUENTA

### REPLICAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C2.LIBRARY.GLOBALNET

#### Acciones

- IF m_CUENTAS = GLOBAL_GAS.BE:C2.LIBRARY.GLOBALNET.DESCARGAR_CUENTAS ()
    - GLOBAL_GAS.BE:C3.STEP.CAT.CUENTAS.ELIMINAR_TODOS ( )
    - FOREACH m_CUENTAS AS m_UNA_CUENTA
        - GLOBAL_GS.BE:C3.STEP.CAT.CUENTAS.AGREGAR ( ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, NOMBRE, APELLIDO_PATERNO, ID_CLIENTE, NOMBRE, NUMERO, TELEFONO, DOMICILIO )
            - ID_GLOBALNET : m_UN_CLIENTE.ID_GLOBALNET,
            - FECHA_ULTIMA_MODIFICACION : m_UN_CLIENTE.FECHA_ULTIMA_MODIFICACION
            - NOMBRE : m_UN_CLIENTE.NOMBRE
            - APELLIDO_PATERNO : m_UN_CLIENTE.APELLIDO_PATERNO
            - ID_CLIENTE : m_UN_CLIENTE.ID_CLIENTE
            - NUMERO : m_UN_CLIENTE.NUMERO
            - TELEFONO : m_UN_CLIENTE.TELEFONO
            - DOMICLIO : m_UN_CLIENTE.DOMICILIO

#### Retorno

- N/A

### CONSULTAR[POST]

#### Acciones

- TRY
    - m_CUENTAS = QUERY - SELECT * FROM cat_cuentas WHERE CLIENTE = PARAM.ID_CLIENTE
- CATCH
    - RETROW

- RETURN m_CUENTAS

#### Retorno

- m_CUENTAS
    - ID_CUENTA : m_CUENTA.CUE_ID
    - DOMICILIO : m_CUENTA.DOMICILIO
    - NOMBRE : m_CUENTA.NOMBRE
    - TIPO_SERVICIO : m_CUENTA.TIPO_SERVICIO
    - NUMERO : m_CUENTA.NUMERO

+ Attribute
    - ID_CLIENTE

## DAT.SERVICIOS [/dat.servicios]

### AGREGAR[POST]

#### Librerias

- GLOBAL_GAS.BE:C2.LIBRARY.CLIENTES

#### Acciones

- TRY
    - o_CLIENTE = NEW CLIENTE ( ID_CLIENTE )
        - ID_CLIENTE : PARAM.ID_CLIENTE
    - o_CUENTA = NEW CUENTA ( ID_CUENTA )
        - ID_CUENTA : PARAM.ID_CUENTA
    - IF( o_CLIENTE.VALIDAR_SESION () )
        - GLOBAL_GAS.BE:C3.STEP.DAT.SERVICIOS.AGREGAR ( ID_CUENTA, ID_CLIENTE, DETALLES )
            - ID_CUENTA : PARAM.ID_CUENTA
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - DETALLES : PARAM.DETALLES
- CATCH
    - RETROW

#### Retorno    

- N/A

+ Attribute
    - ID_CLIENTE
    - ID_CUENTA
    - DETALLES
