FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Cliente Global Gas - C3

## CAT.CLIENTES [/cat.clientes]

### ELIMINAR_TODOS [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.ELIMINAR_TODOS()

#### Retorno

- N/A

### AGREGAR [POST]

#### Acciones

- IF(APELLIDO_PATERNO IS NUMERIC)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.ASIGNAR_ID_GLOBALNET ( ID_CLIENTE, ID_GLOBALNET )
        - ID_CLIENTE: PARAM.ID_CLIENTE
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
- ELSE IF(ID_GLOBALNET != NULL)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, NUMERO, TELEFONO, ID_GLOBALNET, DOMICILIO )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - NUMERO: PARAM.NUMERO
        - TELEFONO: PARAM.TELEFONO
        - ID_GLOBALNET: PARAM.GLOBALNET
- ELSE 
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, TELEFONO )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - TELEFONO: PARAM.TELEFONO
    - e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
        - FECHA_HORA: PARAM.FECHA_HORA
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO

#### Retorno
    
- N/A

+ Attribute
    - ID_CLIENTE
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NOMBRE
    - NUMERO
    - TELEFONO
    - APELLIDO_PATENO
    - DOMICILIO

### GENERAR_CODIGO [POST]

#### Acciones

- GLOBAL_GAS.BE.C4.WRITE.SH.SMS.ENVIAR_MENSAJE ( MENSAJE, TELEFONO)
    - MENSAJE : EVALUAR_MENSAJE ( CODIGO )
    - TELEFONO : PARAM.TELEFONO
- GLOBAL_GAS.BE.C4.WRITE.DB.CAT_CLIENTES_CODIGOS.AGREGAR ( CODIGO, TELEFONO )
    - CODIGO : GENERAR_CODIGO(4)
    - TELEFONO : PARAM.TELEFONO
- e_APIKEY : GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES_ACCESOS.GENERAR_APIKEY ( TELEFONO )
    - TELEFONO : PARAM.TELEFONO
    

#### Retorno

- e_APIKEY

+ Attribute
    -TELEFONO

### VALIDAR_CODIGO

#### Acciones

- IF QUERY - !SELECT CLI_COD_ID FROM dat_clientes_codigos WHERE CLI_COD_TELEFONO = PARAM.TELEFONO AND CLI_COD_CODIGO = PARAM.CODIGO AND CLI_COD_VIGENCIA > DATE()
    RETROW 
- IF QUERY - SELECT CLI_ID, CLI_NUMERO_CUENTA  FROM cat_clientes INNER JOIN cat_cliente_accesos ON CLI_ACC_TELEFONO = CLI_TELEFONO WHERE CLI_TELEFONO = PARAM.TELEFONO AND CLI_APIKEY = PARAM.APIKEY
    - e_JWT = GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTE.OBTENER_JWT ( QUERY - CLI_ID )
- ELSE
    RETURN TRUE;

#### Retorno

- e_JWT
- TRUE

+ Attribute
    - TELEFONO
    - CODIGO
    - APIKEY

### ACTUALIZAR [POST]

#### Acciones

- IF(APELLIDO_PATERNO IS NUMERIC)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.ASIGNAR_ID_GLOBALNET ( ID_CLIENTE, ID_GLOBALNET )
        - ID_CLIENTE: PARAM.ID_CLIENTE
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
- ELSE IF(ID_GLOBALNET != NULL)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, NUMERO, TELEFONO, ID_GLOBALNET )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - NUMERO: PARAM.NUMERO
        - TELEFONO: PARAM.TELEFONO
        - ID_GLOBALNET: PARAM.GLOBALNET
- ELSE 
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, TELEFONO )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - TELEFONO: PARAM.TELEFONO
    - e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
        - FECHA_HORA: PARAM.FECHA_HORA
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO

#### Retorno
    
- N/A

+ Attribute
    - ID_CLIENTE
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NOMBRE
    - NUMERO
    - TELEFONO    

### OBTENER_JWT[POST]
    
#### Acciones

- e_JWT = GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTE.OBTENER_JWT ( ID_CLIENTE )

#### Retorno

- N/A

+ Attribute
    - ID_CLIENTE

## CAT.CLIENTES.ACCESOS [/cat.clientes.accesos]

### GENERAR_APIKEY

#### Acciones

- e_APIKEY : GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES_ACCESOS.GENERAR_APIKEY ( TELEFONO )
    - TELEFONO : PARAM.TELEFONO

#### Retorno

- e_APIKEY

+ Attribute
    - TELEFONO

## CAT.CUENTAS [/cat.cuentas]

### AGREGAR [POST] 
    
- IF ( GLOBAL['USUARI'] != null )
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.AGREGAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO )
        - DOMICILIO : PARAM.DOMICILIO
        - TIPO_SERVICIO : PARAM.DOMICILIO
        - TELEFONO : PARAM.TELEFONO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CLCLO
    - e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'CUENTA.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - CLIENTE : PARAM.CLIENTE
            - CICLO : PARAM.CICLO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
        - FECHA_HORA: PARAM.FECHA_HORA
        - DETALLES
            - TIPO: 'CUENTA.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - CLIENTE : PARAM.CLIENTE
            - CICLO : PARAM.CICLO
- ELSE IF ( ID_GLOBALNET != NULL ) 
    GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.ASIGNAR_ID_GLOBALNET 
        - CLIENTE_ID : PARAM.CLIENTE_ID
        - ID_GLOBALNET : PARAM.ID_GLOBALNET
- ELSE 
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.AGREGAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO, ID_GLOBALNET ) 
        - DOMICILIO : PARAM.DOMICILIO
        - TIPO_SERVICIO : PARAM.TIPO_SERVICIO
        - TELEFONO : PARAM.TELEFONO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CICLO
        - ID_GLOBALNET : PARAM.ID_GLOBALNET

#### Retorno

- N/A

+ Attribute
    - DOMICILIO
    - TIPO_SERVICIO
    - TELEFONO
    - CLIENTE
    - CICLO
    - ID_GLOBALNET

### ACTUALIZAR[POST]            
            
#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.ACTUALIZAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO, ID_CUENTA )
    - DOMICILIO : PARAM.DOMICILIO
    - TIPO_SERVICIO : PARAM.DOMICILIO
    - TELEFONO : PARAM.TELEFONO
    - CLIENTE : PARAM.CLIENTE
    - CICLO : PARAM.CLCLO
- e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
    - DETALLES
        - TIPO: 'CUENTA.ACTUALIZAR'
        - NOMBRE: PARAM.NOMBRE
        - TELEFONO: PARAM.TELEFONO
        - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CICLO
- GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
    - FECHA_HORA: PARAM.FECHA_HORA
    - DETALLES
        - TIPO: 'CUENTA.ACTUALIZAR'
        - NOMBRE: PARAM.NOMBRE
        - TELEFONO: PARAM.TELEFONO
        - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CICLO    

#### Retorno

- N/A

+ Attribute
    - DOMICILIO
    - TIPO_SERVICIO
    - TELEFONO
    - CLIENTE
    - ID_CUENTA
    - CICLO
    - ID_GLOBALNET    

### ELIMINAR

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.ELIMINAR ( ID_CUENTA )
    - ID_CUENTA : PARAMS.ID_CUENTA

#### Retorno

- N/A

+ Attribute
    - ID_CUENTA

### ELIMINAR_TODOS

#### Acciones

- GLOBAL_GA.BE:C4.WRITE.DB.CAT_CUENTAS.ELIMINAR_TODOS ( )

#### Retorno

- N/A

## DAT.SERVICIOS [/dat.servicios]

### AGREGAR[POST]

#### Acciones
- IF( $GLOBAL[USUARIO] != NULL ) 
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT.ASIGNAR_ID_GLOBALNET ( ID_GLOBALNET, ID_SERVICIO ) 
- ELSE 
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.AGREGAR ( ID_CLIENTE, ID_CUENTA, DETALLES )
        - ID_CLIENTE : PARAM.ID_CLIENTE
        - ID_CUENTA : PARAM.ID_CUENTA
        - DETALLES : PARAM.DETALLES
    -e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'SERVICIO.AGREGAR'
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( FECHA_HORA, DETALLES )
        - FECHA_HORA : e_FECHA_HORA
        - DETALLES
            - TIPO: 'SERVICIO.AGREGAR'
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA      

#### Retorno

- N/A            

+ Attribute
    - ID_CLIENTE
    - ID_CUENTA
    - ID_SERVICIO
    - DETALLES

### ACTUALIZAR[POST]

#### Acciones

- IF ( QUERY - SELECT ESTADO FROM dat_servicios WHERE ID_SERVICIO=PARAM.ID_SERVICIO AND ESTADO = 'PENDIENTE'
    - EXCEPCION ESTADO PENDIENTE
- ELSE 
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.ACTUALIZAR ( ID_SERVICIO, ID_CUENTA, ID_CLIENTE, ESTADO, DETALLES )
        - ID_CUENTA : PARAM.ID_CUENTA
        - ID_CLIENTE : PARAM.ID_CLIENTE
        - ESTADO : PARAM.ESTADO
        - DETALLES : PARAM.DETALLES
    -e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'SERVICIO.ACTUALIZAR'
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
            - ESTADO : PARAM.ESTADO
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( FECHA_HORA, DETALLES )
        - FECHA_HORA : e_FECHA_HORA
        - DETALLES
            - TIPO: 'SERVICIO.ACTUALIZAR'
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
            - ESTADO : PARAM.ESTADO
            - ID_GLOBALNET : PARAM.ID_GLOBALNET

#### Retorno

- N/A
- EXCEPTION

+ Attribute
    - ID_CLIENTE
    - ID_CUENTA
    - ID_SERVICIO
    - ESTADO
    - DETALLES
