FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Cliente Global Gas - C3

## CAT.CLIENTES [/cat.clientes]

### ELIMINAR_TODOS [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.ELIMINAR_TODOS()

#### Retorno

- N/A

### AGREGAR [POST]

#### Acciones

- IF(APELLIDO_PATERNO IS NUMERIC)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.ASIGNAR_ID_GLOBALNET ( ID_CLIENTE, ID_GLOBALNET )
        - ID_CLIENTE: PARAM.ID_CLIENTE
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - NUMERO : PARAM.NUMERO
- ELSE IF(ID_GLOBALNET != NULL)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, NUMERO, TELEFONO, ID_GLOBALNET, DOMICILIO )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - NUMERO: PARAM.NUMERO
        - TELEFONO: PARAM.TELEFONO
        - ID_GLOBALNET: PARAM.GLOBALNET
- ELSE 
    - e_HASH = md5("CLIENTE.AGREGAR{PARAM.NOMBRE}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.TELEFONO}")
    - IF QUERY - SELECT COL_GLO_ID FROM log_cola_globalnet WHERE COL_GLO_HASH='HASH'
        - RETURN
    - e_ID = GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, TELEFONO )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - TELEFONO: PARAM.TELEFONO
    - e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
        - FECHA_HORA: PARAM.FECHA_HORA
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
        - HASH    
    - e_JWT = GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTE.OBTENER_JWT ( e_ID )        

#### Retorno
    
- e_JWT

+ Attribute
    - ID_CLIENTE
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NOMBRE
    - NUMERO
    - TELEFONO
    - APELLIDO_PATENO
    - DOMICILIO

### GENERAR_CODIGO [POST]

#### Acciones

- GLOBAL_GAS.BE.C4.WRITE.SH.SMS.ENVIAR_MENSAJE ( MENSAJE, TELEFONO)
    - MENSAJE : EVALUAR_MENSAJE ( CODIGO )
    - TELEFONO : PARAM.TELEFONO
- GLOBAL_GAS.BE.C4.WRITE.DB.CAT_CLIENTES_CODIGOS.AGREGAR ( CODIGO, TELEFONO )
    - CODIGO : GENERAR_CODIGO(4)
    - TELEFONO : PARAM.TELEFONO
- e_APIKEY : GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES_ACCESOS.GENERAR_APIKEY ( TELEFONO )
    - TELEFONO : PARAM.TELEFONO
    

#### Retorno

- e_APIKEY

+ Attribute
    -TELEFONO

### VALIDAR_CODIGO

#### Acciones

- IF QUERY - !SELECT CLI_COD_ID FROM dat_clientes_codigos WHERE CLI_COD_TELEFONO = PARAM.TELEFONO AND CLI_COD_CODIGO = PARAM.CODIGO AND CLI_COD_VIGENCIA > DATE()
    RETROW 
- IF QUERY - SELECT CLI_ID, CLI_NUMERO_CUENTA  FROM cat_clientes INNER JOIN cat_cliente_accesos ON CLI_ACC_TELEFONO = CLI_TELEFONO WHERE CLI_TELEFONO = PARAM.TELEFONO AND CLI_APIKEY = PARAM.APIKEY
    - e_JWT = GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTE.OBTENER_JWT ( QUERY - CLI_ID )
- ELSE
    RETURN TRUE;

#### Retorno

- e_JWT
- TRUE

#### Excepciones

- GLOBAL_GAS.BE:C3.STEP.CAT.CLIENTES.VALIDAR_CODIGO.CODIGO_INVALIDO

+ Attribute
    - TELEFONO
    - CODIGO
    - APIKEY

### ACTUALIZAR [POST]

#### Acciones

- IF(APELLIDO_PATERNO IS NUMERIC)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.ASIGNAR_ID_GLOBALNET ( ID_CLIENTE, ID_GLOBALNET )
        - ID_CLIENTE: PARAM.ID_CLIENTE
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
- ELSE IF(ID_GLOBALNET != NULL)
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, NUMERO, TELEFONO, ID_GLOBALNET )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - NUMERO: PARAM.NUMERO
        - TELEFONO: PARAM.TELEFONO
        - ID_GLOBALNET: PARAM.GLOBALNET
- ELSE 
    - e_HASH = md5("CLIENTE.ACTUALIZAR{PARAM.NOMBRE}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.TELEFONO}")
    - IF QUERY - SELECT COL_GLO_ID FROM log_cola_globalnet WHERE COL_GLO_HASH='HASH'
        - RETURN
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES.AGREGAR ( FECHA_ULTIMA_MODIFICACION, NOMBRE, TELEFONO )
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - NOMBRE: PARAM.NOMBRE
        - TELEFONO: PARAM.TELEFONO        
    - e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
        - FECHA_HORA: PARAM.FECHA_HORA
        - DETALLES
            - TIPO: 'CLIENTE.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
        - HASH    

#### Retorno
    
- N/A

+ Attribute
    - ID_CLIENTE
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NOMBRE
    - NUMERO
    - TELEFONO    

### OBTENER_JWT[POST]
    
#### Acciones

- e_JWT = GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTE.OBTENER_JWT ( ID_CLIENTE )

#### Retorno

- e_JWT

+ Attribute
    - ID_CLIENTE

## CAT.CLIENTES.ACCESOS [/cat.clientes.accesos]

### GENERAR_APIKEY

#### Acciones

- e_APIKEY : GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CLIENTES_ACCESOS.GENERAR_APIKEY ( TELEFONO )
    - TELEFONO : PARAM.TELEFONO

#### Retorno

- e_APIKEY

+ Attribute
    - TELEFONO

## CAT.CUENTAS [/cat.cuentas]

### AGREGAR [POST] 
    
- IF ( GLOBAL['USUARIO'] != null )
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.AGREGAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO, COORDENADAS )
        - DOMICILIO : PARAM.DOMICILIO
        - TIPO_SERVICIO : PARAM.DOMICILIO
        - TELEFONO : PARAM.TELEFONO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CLCLO
        - COORDENADAS : PARAM.COORDENADAS
    - e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'CUENTA.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - CLIENTE : PARAM.CLIENTE
            - CICLO : PARAM.CICLO
            - COORDENADAS : PARAM.COORDENADAS
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
        - FECHA_HORA: PARAM.FECHA_HORA
        - DETALLES
            - TIPO: 'CUENTA.AGREGAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - CLIENTE : PARAM.CLIENTE
            - CICLO : PARAM.CICLO
            - COORDENADAS : PARAM.COORDENADAS
- ELSE IF ( ID_GLOBALNET != NULL ) 
    GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.ASIGNAR_ID_GLOBALNET 
        - CLIENTE_ID : PARAM.CLIENTE_ID
        - ID_GLOBALNET : PARAM.ID_GLOBALNET
- ELSE 
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.AGREGAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO, ID_GLOBALNET ) 
        - DOMICILIO : PARAM.DOMICILIO
        - TIPO_SERVICIO : PARAM.TIPO_SERVICIO
        - TELEFONO : PARAM.TELEFONO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CICLO
        - ID_GLOBALNET : PARAM.ID_GLOBALNET

#### Retorno

- N/A

+ Attribute
    - DOMICILIO
    - TIPO_SERVICIO
    - TELEFONO
    - CLIENTE
    - CICLO
    - ID_GLOBALNET

### ACTUALIZAR[POST]            
            
#### Acciones

- IF ( GLOBAL['USUARIO'] != null )
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.ACTUALIZAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO, COORDENADAS, ID_CUENTA )
        - DOMICILIO : PARAM.DOMICILIO
        - TIPO_SERVICIO : PARAM.DOMICILIO
        - TELEFONO : PARAM.TELEFONO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CLCLO
        - COORDENADAS : PARAM.COORDENADAS
    - e_HASH = md5("CUENTA.ACTUALIZAR{PARAM.DOMICILIO}{PARAM.TIPO_SERVICIO}{PARAM.TELEFONO}{PARAM.TELEFONO}{PARAM.CLIENTE}{PARAM.CICLO}{PARAM.COORDENADAS}{PARAM.ID_CLIENTE}")
    - IF QUERY - SELECT COL_GLO_ID FROM log_cola_globalnet WHERE COL_GLO_HASH='HASH'
        - RETURN    
    - e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'CUENTA.ACTUALIZAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - CLIENTE : PARAM.CLIENTE
            - CICLO : PARAM.CICLO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( DETALLES, FECHA_HORA )
        - FECHA_HORA: PARAM.FECHA_HORA
        - DETALLES
            - TIPO: 'CUENTA.ACTUALIZAR'
            - NOMBRE: PARAM.NOMBRE
            - TELEFONO: PARAM.TELEFONO
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - CLIENTE : PARAM.CLIENTE
            - CICLO : PARAM.CICLO  
        - HASH : e_HASH      
- ELSE
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.ACTUALIZAR ( DOMICILIO, TIPO_SERVICIO, TELEFONO, CLIENTE, CICLO, COORDENADAS, ID_CUENTA )
        - DOMICILIO : PARAM.DOMICILIO
        - TIPO_SERVICIO : PARAM.DOMICILIO
        - TELEFONO : PARAM.TELEFONO
        - CLIENTE : PARAM.CLIENTE
        - CICLO : PARAM.CLCLO
        - COORDENADAS : PARAM.COORDENADAS

#### Retorno

- N/A

+ Attribute
    - DOMICILIO
    - TIPO_SERVICIO
    - TELEFONO
    - CLIENTE
    - ID_CUENTA
    - CICLO
    - ID_GLOBALNET    

### ELIMINAR

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_CUENTAS.ELIMINAR ( ID_CUENTA )
    - ID_CUENTA : PARAMS.ID_CUENTA

#### Retorno

- N/A

+ Attribute
    - ID_CUENTA

### ELIMINAR_TODOS

#### Acciones

- GLOBAL_GA.BE:C4.WRITE.DB.CAT_CUENTAS.ELIMINAR_TODOS ( )

#### Retorno

- N/A

## DAT.SERVICIOS [/dat.servicios]

### AGREGAR[POST]

#### Acciones
- IF( $GLOBAL[USUARIO] == NULL ) 
    - e_HASH = md5("SERVICIOS.ACTUALIZAR{PARAM.ID_GLOBALNET}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.CLIENTE}{PARAM.CUENTA}{PARAM.CUENTA_OCULTA}{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.TIPO_SERVICIO}{PARAM.FECHA_PROGRAMADO}{PARAM.ESTATUS}{PARAM.DOMICILIO.NOMBRE}{PARAM.DOMICILIO.CALLE}{PARAM.DOMICILIO.NUMERO_EXTERIOR}{PARAM.DOMICILIO.NUMERO_INTERIOR}{PARAM.DOMICILIO.REFERENCIA}{PARAM.DOMICILIO.COLONIA}{PARAM.DOMICILIO.MUNICIPIO}")
    - IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
        - RETURN
    - e_SER_UNIDAD = QUERY - SELECT SER_UNIDAD FROM dat_servicios WHERE SER_ID_GLOBALNET='PARAM.ID_GLOBALNET'
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.ACTUALIZAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, CLIENTE, CUENTA, CUENTA_OCULTA, ID_GLOBALNET_UNIDAD, TIPO_SERVICIO, FECHA_PROGRAMADO, ESTATUS, DOMICILIO)
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - CLIENTE: PARAM.CLIENTE
        - CUENTA: PARAM.CUENTA
        - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
        - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
        - ESTATUS: PARAM.ESTATUS
        - DOMICILIO: PARAM.DOMICILIO
        - INDICE: PARAM.INDICE
        - DESCUENTO: PARAM.DESCUENTO
        - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
    - e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - DETALLES:
            - TIPO: 'SERVICIOS.ACTUALIZAR'
            - ID_GLOBALNET: PARAM.ID_GLOBALNET
            - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
            - CLIENTE: PARAM.CLIENTE
            - CUENTA: PARAM.CUENTA
            - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
            - ESTATUS: PARAM.ESTATUS
            - DOMICILIO: PARAM.DOMICILIO
            - INDICE: PARAM.INDICE
            - DESCUENTO: PARAM.DESCUENTO
            - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
        - FECHAHORA: e_FECHAHORA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - DETALLES:
            - TIPO: 'SERVICIOS.ACTUALIZAR'
            - ID_GLOBALNET: PARAM.ID_GLOBALNET
            - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
            - CLIENTE: PARAM.CLIENTE
            - CUENTA: PARAM.CUENTA
            - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
            - ESTATUS: PARAM.ESTATUS
            - DOMICILIO: PARAM.DOMICILIO
            - INDICE: PARAM.INDICE
            - DESCUENTO: PARAM.DESCUENTO
            - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
        - HASH: e_HASH
    - IF e_SER_UNIDAD != PARAM.ID_GLOBALNET_UNIDAD
        - e_FECHAHORA_CAMBIO_UNIDAD = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
            - ID_GLOBALNET_UNIDAD: SER_UNIDAD
            - DETALLES:
                - TIPO: 'SERVICIOS.ACTUALIZAR'
                - ID_GLOBALNET: PARAM.ID_GLOBALNET
                - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
                - CLIENTE: PARAM.CLIENTE
                - CUENTA: PARAM.CUENTA
                - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
                - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
                - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
                - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
                - ESTATUS: 'CANCELADO'
                - DOMICILIO: PARAM.DOMICILIO
                - INDICE: PARAM.INDICE
                - DESCUENTO: PARAM.DESCUENTO
                - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
        - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
            - FECHAHORA: e_FECHAHORA_CAMBIO_UNIDAD
            - ID_GLOBALNET_UNIDAD: e_SER_UNIDAD
            - DETALLES:
                - TIPO: 'SERVICIOS.ACTUALIZAR'
                - ID_GLOBALNET: PARAM.ID_GLOBALNET
                - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
                - CLIENTE: PARAM.CLIENTE
                - CUENTA: PARAM.CUENTA
                - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
                - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
                - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
                - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
                - ESTATUS: 'CANCELADO'
                - DOMICILIO: PARAM.DOMICILIO
                - INDICE: PARAM.INDICE
                - DESCUENTO: PARAM.DESCUENTO
                - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
            - HASH: e_HASH
    - GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_SERVICIOS_FECHA (FECHAHORA)
        - FECHAHORA: PARAM.FECHA_ULTIMA_ACTUALIZACION
- ELSE 
    - e_HASH = md5("SERVICIOS.AGREGAR{PARAM.ID_GLOBALNET}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.CLIENTE}{PARAM.CUENTA}{PARAM.CUENTA_OCULTA}{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.TIPO_SERVICIO}{PARAM.FECHA_PROGRAMADO}{PARAM.ESTATUS}{PARAM.DOMICILIO.NOMBRE}{PARAM.DOMICILIO.CALLE}{PARAM.DOMICILIO.NUMERO_EXTERIOR}{PARAM.DOMICILIO.NUMERO_INTERIOR}{PARAM.DOMICILIO.REFERENCIA}{PARAM.DOMICILIO.COLONIA}{PARAM.DOMICILIO.MUNICIPIO}")
    - IF QUERY - SELECT COL_GLO_ID FROM log_cola_globalnet WHERE COL_GLO_HASH='HASH'
        - RETURN
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.AGREGAR ( ID_CLIENTE, ID_CUENTA, DETALLES )
        - ID_CLIENTE : PARAM.ID_CLIENTE
        - ID_CUENTA : PARAM.ID_CUENTA
        - DETALLES : PARAM.DETALLES
    -e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'SERVICIO.AGREGAR'
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( FECHA_HORA, DETALLES )
        - FECHA_HORA : e_FECHA_HORA
        - DETALLES
            - TIPO: 'SERVICIO.AGREGAR'
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA  
        - HASH : e_HASH        

#### Retorno

- N/A            

+ Attribute
    - ID_CLIENTE
    - ID_CUENTA
    - ID_SERVICIO
    - DETALLES

### ACTUALIZAR[POST]

#### Acciones

- IF ( $GLOBAL[USUARIO] == NULL )
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.ACTUALIZAR ( ID_SERVICIO, ID_CUENTA, ID_CLIENTE, ESTADO, DETALLES )
        - ID_CUENTA : PARAM.ID_CUENTA
        - ID_CLIENTE : PARAM.ID_CLIENTE
        - ESTADO : PARAM.ESTADO
        - DETALLES : PARAM.DETALLES
    - e_HASH = md5("SERVICIO.ACTUALIZAR{PARAM.ID_SERVICIO}{PARAM.ID_CUENTA}{PARAM.ID_CLIENTE}{PARAM.ESTADO}{PARAM.DETALLES}")
    - IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
        - RETURN    
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.ACTUALIZAR ( ID_SERVICIO, ID_CUENTA, ID_CLIENTE, ESTADO, DETALLES )
        - ID_CUENTA : PARAM.ID_CUENTA
        - ID_CLIENTE : PARAM.ID_CLIENTE
        - ESTADO : PARAM.ESTADO
        - DETALLES : PARAM.DETALLES
    -e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'SERVICIO.ACTUALIZAR'
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
            - ESTADO : PARAM.ESTADO
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( FECHA_HORA, DETALLES )
        - FECHA_HORA : e_FECHA_HORA
        - DETALLES
            - TIPO: 'SERVICIO.ACTUALIZAR'
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
            - ESTADO : PARAM.ESTADO
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
        - HASH    
- ELSE 
    - e_HASH = md5("SERVICIO.ACTUALIZAR{PARAM.ID_SERVICIO}{PARAM.ID_CUENTA}{PARAM.ID_CLIENTE}{PARAM.ESTADO}{PARAM.DETALLES}")
    - IF QUERY - SELECT COL_GLO_ID FROM log_cola_globalnet WHERE COL_GLO_HASH='HASH'
        - RETURN    
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.ACTUALIZAR ( ID_SERVICIO, ID_CUENTA, ID_CLIENTE, ESTADO, DETALLES )
        - ID_CUENTA : PARAM.ID_CUENTA
        - ID_CLIENTE : PARAM.ID_CLIENTE
        - ESTADO : PARAM.ESTADO
        - DETALLES : PARAM.DETALLES
    -e_FECHA_HORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR ( DETALLES )
        - DETALLES
            - TIPO: 'SERVICIO.ACTUALIZAR'
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
            - ESTADO : PARAM.ESTADO
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_GLOBALNET.AGREGAR ( FECHA_HORA, DETALLES )
        - FECHA_HORA : e_FECHA_HORA
        - DETALLES
            - TIPO: 'SERVICIO.ACTUALIZAR'
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
            - ID_CLIENTE : PARAM.ID_CLIENTE
            - ID_CUENTA : PARAM.ID_CUENTA
            - ESTADO : PARAM.ESTADO
            - ID_GLOBALNET : PARAM.ID_GLOBALNET
        - HASH    

#### Retorno

- N/A
- EXCEPTION

+ Attribute
    - ID_CLIENTE
    - ID_CUENTA
    - ID_SERVICIO
    - ESTADO
    - DETALLES
