FORMAT: 1A
HOST: https://globalgas.com

# Global Gas - C1

## CAT.EMPLEADOS [/cat.empleados]

### REPLICAR [POST]

#### Comentarios

- Ejecutado por usuario desde la consola

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA ()
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: PARAM.INSTANCIA
    - GLOBAL_GAS.BE:C2.COMMAND.CAT.EMPLEADOS.REPLICAR ()
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA'
            - RETURN 400-04
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 400-04 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA

#### Excepciones

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.INSTANCIA_INEXISTENTE

+ Attributes
    - INSTANCIA

## CAT.UNIDADES [/cat.unidades]

### REPLICAR [POST]

#### Comentarios

- Ejecutado por usuario desde la consola

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA ()
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: PARAM.INSTANCIA
    - GLOBAL_GAS.BE:C2.COMMAND.CAT.UNIDADES.REPLICAR ()
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA'
            - RETURN 400-04
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 400-04 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA

#### Excepciones

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.INSTANCIA_INEXISTENTE

+ Attributes
    - INSTANCIA

## OPE.SESION [/ope.sesion]

### INICIAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'EMPLEADO'
        - VALOR: PARAM.EMPLEADO
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.ID'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'APIKEY'
        - VALOR: PARAM.APIKEY
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.APIKEY'
        - PARAMETRO: []
    - e_JWT = GLOBAL_GAS.BE:C2.COMMAND.OPE.SESION.INICIAR (EMPLEADO, APIKEY)
        - EMPLEADO: PARAM.EMPLEADO
        - APIKEY: PARAM.APIKEY
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.CONSTRUCTOR.NUMERO_INEXISTENTE'
            - RETURN 402-01
        - CASE '402-02 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_APILEY.APIKEY_INCORRECTO'
            - RETURN 402-02
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
    - jwt: e_JWT
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.CONSTRUCTOR.NUMERO_INEXISTENTE
- 402-02 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_APILEY.APIKEY_INCORRECTO

+ Request (application/json)
    + Headers
        - Instancia

+ Attributes
    - EMPLEADO
    - APIKEY

### DEPURAR [POST]

#### Comentarios

- Debe ser un TASK que se ejecute todos los dias a las 03:00 horas

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION

#### Acciones

- IF r_PLANTAS = QUERY - SELECT PLA_DETALLES->>'$.INSTANCIA' FROM cat_plantas WHERE PLA_ELIMINADO=''
    - WHILE a_UNA_PLANTA = fetch_array(r_PLANTAS)
        - TRY
            - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
                - INSTANCIA: a_UNA_PLANTA.INSTANCIA
            - GLOBAL_GAS.BE:C2.COMMAND.OPE.SESION.DEPURAR ()
        - CATCH
            - CONTINUE

#### Retorno

- 200
    - status: 'success'

+ Attributes
    - INSTANCIA

## OPE.SINCRONIZACION_APLICACION [/ope.sincronizacion_aplicacion]

### CARGAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'DETALLES'
        - VALOR: PARAM.DETALLES
        - OBLIGATORIO: TRUE
        - VALIDACION: 'FUNC.is_array'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C2.COMMAND.OPE.SINCRONIZACION_APLICACION.CARGAR (DETALLES)
        - DETALLES: PARAM.DETALLES
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

+ Attributes
    - DETALLES

### DEPURAR [POST]

#### Comentarios

- Debe ser un TASK que se ejecute todos los dias a las 03:00 horas

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION

#### Acciones

- IF r_PLANTAS = QUERY - SELECT PLA_DETALLES->>'$.INSTANCIA' FROM cat_plantas WHERE PLA_ELIMINADO=''
    - WHILE a_UNA_PLANTA = fetch_array(r_PLANTAS)
        - TRY
            - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
                - INSTANCIA: a_UNA_PLANTA.INSTANCIA
            - GLOBAL_GAS.BE:C2.COMMAND.OPE.COLA_OPERACION.DEPURAR ()
        - CATCH
            - CONTINUE

#### Retorno

- 200
    - status: 'success'

+ Attributes
    - INSTANCIA

## OPE.LIQUIDACIONES [/ope.liquidaciones]

### ASIGNAR_INICIAL_ESTACIONARIO [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'ID_GLOBALNET_UNIDAD'
        - VALOR: PARAM.ID_GLOBALNET_UNIDAD
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.ID'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'FECHAHORA'
        - VALOR: PARAM.FECHAHORA
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.FECHAHORA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'MEDIDOR_INICIAL'
        - VALOR: PARAM.MEDIDOR_INICIAL
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.MONEDA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'ROTOGAUGE_INICIAL'
        - VALOR: PARAM.ROTOGAUGE_INICIAL
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.MONEDA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO (ID_GLOBALNET_UNIDAD, FECHAHORA, MEDIDOR_INICIAL, ROTOGAUGE_INICIAL)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - FECHAHORA: PARAM.FECHAHORA
        - MEDIDOR_INICIAL: PARAM.MEDIDOR_INICIAL
        - ROTOGAUGE_INICIAL: PARAM.ROTOGAUGE_INICIAL
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR'
            - RETURN 402-01
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE'
            - RETURN 402-02
        - CASE 'GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO.FECHAHORA_INVALIDA'
            - RETURN 402-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR
- 402-02 GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE
- 402-03 GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO.FECHAHORA_INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA
    - MEDIDOR_INICIAL
    - ROTOGAUGE_INICIAL

### ASIGNAR_FINAL_ESTACIONARIO [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'ID_GLOBALNET_UNIDAD'
        - VALOR: PARAM.ID_GLOBALNET_UNIDAD
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.ID'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'FECHAHORA'
        - VALOR: PARAM.FECHAHORA
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.FECHAHORA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'MEDIDOR_FINAL'
        - VALOR: PARAM.MEDIDOR_FINAL
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.MONEDA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'ROTOGAUGE_FINAL'
        - VALOR: PARAM.ROTOGAUGE_FINAL
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.MONEDA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO (ID_GLOBALNET_UNIDAD, FECHAHORA, MEDIDOR_FINAL, ROTOGAUGE_FINAL)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - FECHAHORA: PARAM.FECHAHORA
        - MEDIDOR_FINAL: PARAM.MEDIDOR_FINAL
        - ROTOGAUGE_FINAL: PARAM.ROTOGAUGE_FINAL
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR'
            - RETURN 402-01
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE'
            - RETURN 402-02
        - CASE 'GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.ASIGNAR_FINAL_ESTACIONARIO.FECHAHORA_INVALIDA'
            - RETURN 402-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR
- 402-02 GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE
- 402-03 GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.ASIGNAR_FINAL_ESTACIONARIO.FECHAHORA_INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA
    - MEDIDOR_FINAL
    - ROTOGAUGE_FINAL

### VALIDAR_INICIAL_CILINDRO [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'ID_GLOBALNET_UNIDAD'
        - VALOR: PARAM.ID_GLOBALNET_UNIDAD
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.ID'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'FECHAHORA'
        - VALOR: PARAM.FECHAHORA
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.FECHAHORA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.VALIDAR_INICIAL_CILINDRO (ID_GLOBALNET_UNIDAD, FECHAHORA)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - FECHAHORA: PARAM.FECHAHORA
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR'
            - RETURN 402-01
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE'
            - RETURN 402-02
        - CASE 'GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.VALIDAR_INICIAL_CILINDRO.FECHAHORA_INVALIDA'
            - RETURN 402-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR
- 402-02 GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE
- 402-03 GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.VALIDAR_INICIAL_CILINDRO.FECHAHORA_INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA

### VALIDAR_FINAL_CILINDRO [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'ID_GLOBALNET_UNIDAD'
        - VALOR: PARAM.ID_GLOBALNET_UNIDAD
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.ID'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'FECHAHORA'
        - VALOR: PARAM.FECHAHORA
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.FECHAHORA'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.VALIDAR_FINAL_CILINDRO (ID_GLOBALNET_UNIDAD, FECHAHORA)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - FECHAHORA: PARAM.FECHAHORA
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR'
            - RETURN 402-01
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE'
            - RETURN 402-02
        - CASE 'GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.VALIDAR_FINAL_CILINDRO.FECHAHORA_INVALIDA'
            - RETURN 402-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR
- 402-02 GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE
- 402-03 GLOBAL_GAS.BE:C2.COMMAND.OPE.LIQUIDACIONES.VALIDAR_FINAL_CILINDRO.FECHAHORA_INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA

## OPE.SINCRONIZACION_GLOBALNET [/ope.sincronizacion_globalnet]

### INICIAR_AGENTE_DESCARGA [POST]

#### Comentarios

- Ejecutado por usuario desde la consola

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA ()
    - IF r_PLANTAS = QUERY - SELECT PLA_DETALLES->>'$.INSTANCIA' FROM cat_plantas WHERE PLA_ELIMINADO=''
        - WHILE a_UNA_PLANTA = fetch_array(r_PLANTAS)
            - GLOBAL_GAS.BE:C2.COMMAND.OPE.SINCRONIZACION_GLOBALNET.INICIAR_AGENTE_DESCARGA (INSTANCIA)
                - INSTANCIA: a_UNA_PLANTA.INSTANCIA
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA'
            - RETURN 400-04
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-04 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA

### INICIAR_AGENTE_CARGA [POST]

#### Comentarios

- Ejecutado por usuario desde la consola

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA ()
    - IF r_PLANTAS = QUERY - SELECT PLA_DETALLES->>'$.INSTANCIA' FROM cat_plantas WHERE PLA_ELIMINADO=''
        - WHILE a_UNA_PLANTA = fetch_array(r_PLANTAS)
            - GLOBAL_GAS.BE:C2.COMMAND.OPE.SINCRONIZACION_GLOBALNET.INICIAR_AGENTE_CARGA (INSTANCIA)
                - INSTANCIA: a_UNA_PLANTA.INSTANCIA
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA'
            - RETURN 400-04
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-04 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA

### EJECUTAR_AGENTE_DESCARGA [POST]

#### Comentarios

- Ejecutado por usuario desde la consola

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA ()
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: PARAM.INSTANCIA
    - GLOBAL_GAS.BE:C2.COMMAND.OPE.SINCRONIZACION_GLOBALNET.EJECUTAR_AGENTE_DESCARGA ()
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA'
            - RETURN 400-04
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 400-04 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA

+ Attributes
    - INSTANCIA

### EJECUTAR_AGENTE_CARGA [POST]

#### Comentarios

- Ejecutado por usuario desde la consola

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA ()
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: PARAM.INSTANCIA
    - GLOBAL_GAS.BE:C2.COMMAND.OPE.SINCRONIZACION_GLOBALNET.EJECUTAR_AGENTE_CARGA ()
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA'
            - RETURN 400-04
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 400-04 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.VALIDAR_EJECUCION_CONSOLA.EJECUCION_INVALIDA

+ Attributes
    - INSTANCIA

## CON.EMPLEADOS [/con.empleados]

### OBTENER_APIKEY [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'NUMERO'
        - VALOR: PARAM.NUMERO
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.ID'
        - PARAMETRO: []
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'CONTRASENA'
        - VALOR: PARAM.CONTRASENA
        - OBLIGATORIO: TRUE
        - VALIDACION: ''
        - PARAMETRO: []
    - e_APIKEY = GLOBAL_GAS.BE:C2.COMMAND.CON.EMPLEADOS.OBTENER_APIKEY (NUMERO, APIKEY)
        - NUMERO: PARAM.NUMERO
        - APIKEY: PARAM.APIKEY
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.CONSTRUCTOR.NUMERO_INEXISTENTE'
            - RETURN 402-01
        - CASE '402-02 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_CONTRASENA.CONTRASENA_INCORRECTA'
            - RETURN 402-02
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
    - apikey: e_APIKEY
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.CONSTRUCTOR.NUMERO_INEXISTENTE
- 402-02 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_CONTRASENA.CONTRASENA_INCORRECTA

+ Request (application/json)
    + Headers
        Instancia

+ Attributes
    - NUMERO
    - CONTRASENA

### CONSULTAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - m_EMPLEADO = GLOBAL_GAS.BE:C2.COMMAND.CON.EMPLEADOS.CONSULTAR ()
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
    - empleado: m_EMPLEADO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

## CON.UNIDADES [/con.unidades]

### CONSULTAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - m_UNIDADES = GLOBAL_GAS.BE:C2.COMMAND.CON.UNIDADES.CONSULTAR ()
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR'
            - RETURN 402-01
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
    - unidades: m_UNIDADES
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.EMPLEADO.VALIDAR_SUPERVISOR.NO_SUPERVISOR

+ Request (application/json)
    + Headers
        Authorization
        Instancia

## CON.SINCRONIZACION_APLICACION [/con.sincronizacion_aplicacion]

### DESCARGAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - m_DETALLES = GLOBAL_GAS.BE:C2.COMMAND.CON.EMPLEADOS.CONSULTAR (A_PARTIR_DE)
        - A_PARTIR_DE: PARAM.A_PARTIR_DE
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
    - detalles: m_DETALLES
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

+ Attributes
    - A_PARTIR_DE

## CON.SESION [/con.sesion]

### VALIDAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA

+ Request (application/json)
    + Headers
        Authorization
        Instancia

## CON.LIQUIDACIONES [/con.liquidaciones]

### CONSULTAR [POST]

#### Librerias

- GLOBAL_GAS.BE:C1.LIBRARY.CONEXION
- GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION
- GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR (INSTANCIA)
        - INSTANCIA: HEADER.Instancia
    - GLOBAL_GAS.BE:C1.LIBRARY.AUTENTICACION.VALIDAR_SESION (JWT)
        - JWT: HEADER.Authorization
    - GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR (NOMBRE, VALOR, OBLIGATORIO, VALIDACION, PARAMETRO)
        - NOMBRE: 'ID_GLOBALNET_UNIDAD'
        - VALOR: PARAM.ID_GLOBALNET_UNIDAD
        - OBLIGATORIO: TRUE
        - VALIDACION: 'REGEXP.ID'
        - PARAMETRO: []
    - m_LIQUIDACION = GLOBAL_GAS.BE:C2.COMMAND.CON.LIQUIDACIONES.CONSULTAR (ID_GLOBALNET_UNIDAD)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
- CATCH
    - SWITCH
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION'
            - RETURN 400-03
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA'
            - RETURN 401-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO'
            - RETURN 400-01
        - CASE 'GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO'
            - RETURN 400-02
        - CASE 'GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE'
            - RETURN 402-01
        - DEFAULT
            - RETURN 500

#### Retorno

- 200
    - status: 'success'
    - liquidacion: m_LIQUIDACION    
- 400-01 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.OBLIGATORIO
- 400-02 GLOBAL_GAS.BE:C1.LIBRARY.VALIDACION.VALIDAR.INVALIDO
- 400-03 GLOBAL_GAS.BE:C1.LIBRARY.CONEXION.CONECTAR.ERROR_CONEXION
- 401-01 GLOBAL_GAS.BE:C1.LIBRARY.AUTORIZACION.VALIDAR_SESION.INVALIDA
- 402-01 GLOBAL_GAS.BE:C2.LIBRARY.UNIDAD.CONSTRUCTOR.UNIDAD_INEXISTENTE

+ Request (application/json)
    + Headers
        Authorization
        Instancia

+ Attributes
    - ID_GLOBALNET_UNIDAD