FORMAT: 1A
HOST: https://globalgas.com

# Global Gas - C3

## CAT.EMPLEADOS [/cat.empleados]

### AGREGAR [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_EMPLEADOS.AGREGAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, NOMBRE, NUMERO, TELEFONO)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - NOMBRE: PARAM.NOMBRE
    - NUMERO: PARAM.NUMERO
    - TELEFONO: PARAM.TELEFONO
- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_EMPLEADOS_ACCESO.GENERAR_APIKEY (NUMERO)
    - NUMERO: PARAM.NUMERO
- GLOBAL_GAS.BE:C4.WRITE.FS.CAT_EMPLEADOS.GUARDAR (ID_GLOBALNET, IMAGEN)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - IMAGEN: PARAM.IMAGEN
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_EMPLEADOS_ID (ID_GLOBALNET)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NOMBRE
    - NUMERO
    - TELEFONO
    - IMAGEN

### ACTUALIZAR [POST]

#### Acciones

- e_REGISTRO_AGREGADO = GLOBAL_GAS.BE:C4.WRITE.DB.CAT_EMPLEADOS.ACTUALIZAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, NOMBRE, NUMERO, TELEFONO)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - NOMBRE: PARAM.NOMBRE
    - NUMERO: PARAM.NUMERO
    - TELEFONO: PARAM.TELEFONO
- IF e_REGISTRO AGREGADO
    - GLOBAL_GAS.BE:C4.WRITE.DB.CAT_EMPLEADOS_ACCESO.GENERAR_APIKEY (NUMERO)
        - NUMERO: PARAM.NUMERO
- GLOBAL_GAS.BE:C4.WRITE.FS.CAT_EMPLEADOS.GUARDAR (ID_GLOBALNET, IMAGEN)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - IMAGEN: PARAM.IMAGEN
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_EMPLEADOS_FECHA (FECHAHORA)
    - FECHAHORA: PARAM.FECHA_ULTIMA_MODIFICACION

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NOMBRE
    - NUMERO
    - TELEFONO
    - IMAGEN

### ELIMINAR_TODOS [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_EMPLEADOS.ELIMINAR_TODOS ()
- GLOBAL_GAS.BE:C4.WRITE.FS.CAT_EMPLEADOS.ELIMINAR_TODOS ()
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_EMPLEADOS_ID (ID_GLOBALNET)
    - ID_GLOBALNET: '0'
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_EMPLEADOS_FECHA (FECHAHORA)
    - FECHAHORA: date()

#### Retorno

- N/A

## CAT.UNIDADES [/cat.unidades]

### AGREGAR [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_UNIDADES.AGREGAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, NUMERO_ECONOMICO, ID_CHOFER, ID_AYUDANTE, ID_AYUDANTE_2, ID_RUTA, TIPO_UNIDAD, CUENTALITROS, ROTOGAUGE, DOTACION)
    - ID_GLOBALNET: PARAM. ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - NUMERO_ECONOMICO: PARAM.NUMERO_ECONOMICO
    - ID_CHOFER: PARAM.ID_CHOFER
    - ID_AYUDANTE: PARAM.ID_AYUDANTE
    - ID_AYUDANTE_2: PARAM.ID_AYUDANTE_2
    - ID_RUTA: PARAM.ID_RUTA
    - TIPO_UNIDAD: PARAM.TIPO_UNIDAD
    - CUENTALITROS: PARAM.CUENTALITROS
    - ROTOGAUGE: PARAM.ROTOGAUGE
    - DOTACION: PARAM.DOTACION
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_UNIDADES_ID (ID_GLOBALNET)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NUMERO_ECONOMICO
    - ID_CHOFER
    - ID_AYUDANTE
    - ID_AYUDANTE_2
    - ID_RUTA
    - TIPO_UNIDAD
    - CUENTALITROS
    - ROTOGAUGE
    - DOTACION
        - CANTIDAD_10
        - CANTIDAD_20
        - CANTIDAD_30
        - CANTIDAD_45

### ACTUALIZAR [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_UNIDADES.ACTUALIZAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, NUMERO_ECONOMICO, ID_CHOFER, ID_AYUDANTE, ID_AYUDANTE_2, ID_RUTA, TIPO_UNIDAD, CUENTALITROS, ROTOGAUGE, DOTACION)
    - ID_GLOBALNET: PARAM. ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - NUMERO_ECONOMICO: PARAM.NUMERO_ECONOMICO
    - ID_CHOFER: PARAM.ID_CHOFER
    - ID_AYUDANTE: PARAM.ID_AYUDANTE
    - ID_AYUDANTE_2: PARAM.ID_AYUDANTE_2
    - ID_RUTA: PARAM.ID_RUTA
    - TIPO_UNIDAD: PARAM.TIPO_UNIDAD
    - CUENTALITROS: PARAM.CUENTALITROS
    - ROTOGAUGE: PARAM.ROTOGAUGE
    - DOTACION: PARAM.DOTACION
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_UNIDADES_FECHA (FECHAHORA)
    - FECHAHORA: PARAM.FECHA_ULTIMA_MODIFICACION

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - NUMERO_ECONOMICO
    - ID_CHOFER
    - ID_AYUDANTE
    - ID_AYUDANTE_2
    - ID_RUTA
    - TIPO_UNIDAD
    - CUENTALITROS
    - ROTOGAUGE
    - DOTACION
        - CANTIDAD_10
        - CANTIDAD_20
        - CANTIDAD_30
        - CANTIDAD_45

### ELIMINAR_TODOS [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CAT_UNIDADES.ELIMINAR_TODOS ()
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_UNIDADES_ID (ID_GLOBALNET)
    - ID_GLOBALNET: '0'
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_UNIDADES_FECHA (FECHAHORA)
    - FECHAHORA: date()

#### Retorno

- N/A

## OPE.PRECIOS [/ope.precios]

### AGREGAR [POST]

#### Acciones

- e_HASH = md5("PRECIOS.AGREGAR{PARAM.ID_GLOBALNET}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.INDICE}{PARAM.PRODUCTO}{PARAM.ANIO}{PARAM.MES}{PARAM.PRECIO_NETO}")
- IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_PRECIOS.AGREGAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, INDICE, PRODUCTO, ANIO, MES, PRECIO_NETO)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - INDICE: PARAM.INDICE
    - PRODUCTO: PARAM.PRODUCTO
    - ANIO: PARAM.ANIO
    - MES: PARAM.MES
    - PRECIO_NETO: PARAM.PRECIO_NETO
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
    - ID_GLOBALNET_UNIDAD: '0'
    - DETALLES:
        - TIPO: 'PRECIOS.AGREGAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - INDICE: PARAM.INDICE
        - PRODUCTO: PARAM.PRODUCTO
        - ANIO: PARAM.ANIO
        - MES: PARAM.MES
- GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - ID_GLOBALNET_UNIDAD: '0'
    - DETALLES:
        - TIPO: 'PRECIOS.AGREGAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - INDICE: PARAM.INDICE
        - PRODUCTO: PARAM.PRODUCTO
        - ANIO: PARAM.ANIO
        - MES: PARAM.MES
    - HASH: e_HASH
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_PRECIOS_ID (ID_GLOBALNET)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - INDICE
    - PRODUCTO
    - ANIO
    - MES
    - PRECIO_NETO

### ACTUALIZAR [POST]

#### Acciones

- e_HASH = md5("PRECIOS.ACTUALIZAR{PARAM.ID_GLOBALNET}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.INDICE}{PARAM.PRODUCTO}{PARAM.ANIO}{PARAM.MES}{PARAM.PRECIO_NETO}")
- IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_PRECIOS.ACTUALIZAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, INDICE, PRODUCTO, ANIO, MES, PRECIO_NETO)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - INDICE: PARAM.INDICE
    - PRODUCTO: PARAM.PRODUCTO
    - ANIO: PARAM.ANIO
    - MES: PARAM.MES
    - PRECIO_NETO: PARAM.PRECIO_NETO
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
    - ID_GLOBALNET_UNIDAD: '0'
    - DETALLES:
        - TIPO: 'PRECIOS.ACTUALIZAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - INDICE: PARAM.INDICE
        - PRODUCTO: PARAM.PRODUCTO
        - ANIO: PARAM.ANIO
        - MES: PARAM.MES
- GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - ID_GLOBALNET_UNIDAD: '0'
    - DETALLES:
        - TIPO: 'PRECIOS.ACTUALIZAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - INDICE: PARAM.INDICE
        - PRODUCTO: PARAM.PRODUCTO
        - ANIO: PARAM.ANIO
        - MES: PARAM.MES
    - HASH: e_HASH
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_PRECIOS_FECHA (FECHAHORA)
    - FECHAHORA: PARAM.FECHA_ULTIMA_MODIFICACION

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - INDICE
    - PRODUCTO
    - ANIO
    - MES
    - PRECIO_NETO

## OPE.SERVICIOS [/ope.servicios]

### AGREGAR [POST]

#### Acciones

- e_HASH = md5("SERVICIOS.AGREGAR{PARAM.ID_GLOBALNET}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.CLIENTE}{PARAM.CUENTA}{PARAM.CUENTA_OCULTA}{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.TIPO_SERVICIO}{PARAM.FECHA_PROGRAMADO}{PARAM.ESTATUS}{PARAM.DOMICILIO.NOMBRE}{PARAM.DOMICILIO.CALLE}{PARAM.DOMICILIO.NUMERO_EXTERIOR}{PARAM.DOMICILIO.NUMERO_INTERIOR}{PARAM.DOMICILIO.REFERENCIA}{PARAM.DOMICILIO.COLONIA}{PARAM.DOMICILIO.MUNICIPIO}")
- IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.AGREGAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, CLIENTE, CUENTA, CUENTA_OCULTA, ID_GLOBALNET_UNIDAD, TIPO_SERVICIO, FECHA_PROGRAMADO, ESTATUS, DOMICILIO)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - CLIENTE: PARAM.CLIENTE
    - CUENTA: PARAM.CUENTA
    - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
    - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
    - ESTATUS: PARAM.ESTATUS
    - DOMICILIO: PARAM.DOMICILIO
    - INDICE: PARAM.INDICE
    - DESCUENTO: PARAM.DESCUENTO
    - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'SERVICIOS.AGREGAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - CLIENTE: PARAM.CLIENTE
        - CUENTA: PARAM.CUENTA
        - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
        - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
        - ESTATUS: PARAM.ESTATUS
        - DOMICILIO: PARAM.DOMICILIO
        - INDICE: PARAM.INDICE
        - DESCUENTO: PARAM.DESCUENTO
        - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
- GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'SERVICIOS.AGREGAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - CLIENTE: PARAM.CLIENTE
        - CUENTA: PARAM.CUENTA
        - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
        - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
        - ESTATUS: PARAM.ESTATUS
        - DOMICILIO: PARAM.DOMICILIO
        - INDICE: PARAM.INDICE
        - DESCUENTO: PARAM.DESCUENTO
        - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
    - HASH: e_HASH
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_SERVICIOS_ID (ID_GLOBALNET)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - CLIENTE
    - CUENTA
    - CUENTA_OCULTA
    - ID_GLOBALNET_UNIDAD
    - TIPO_SERVICIO
    - FECHA_PROGRAMADO
    - ESTATUS
    - DOMICILIO
    - INDICE
    - DESCUENTO
    - APLICA_CREDITO

### ACTUALIZAR [POST]

#### Acciones

- e_HASH = md5("SERVICIOS.ACTUALIZAR{PARAM.ID_GLOBALNET}{PARAM.FECHA_ULTIMA_MODIFICACION}{PARAM.CLIENTE}{PARAM.CUENTA}{PARAM.CUENTA_OCULTA}{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.TIPO_SERVICIO}{PARAM.FECHA_PROGRAMADO}{PARAM.ESTATUS}{PARAM.DOMICILIO.NOMBRE}{PARAM.DOMICILIO.CALLE}{PARAM.DOMICILIO.NUMERO_EXTERIOR}{PARAM.DOMICILIO.NUMERO_INTERIOR}{PARAM.DOMICILIO.REFERENCIA}{PARAM.DOMICILIO.COLONIA}{PARAM.DOMICILIO.MUNICIPIO}")
- IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
    - RETURN
- e_SER_UNIDAD = QUERY - SELECT SER_UNIDAD FROM dat_servicios WHERE SER_ID_GLOBALNET='PARAM.ID_GLOBALNET'
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.ACTUALIZAR (ID_GLOBALNET, FECHA_ULTIMA_MODIFICACION, CLIENTE, CUENTA, CUENTA_OCULTA, ID_GLOBALNET_UNIDAD, TIPO_SERVICIO, FECHA_PROGRAMADO, ESTATUS, DOMICILIO)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
    - CLIENTE: PARAM.CLIENTE
    - CUENTA: PARAM.CUENTA
    - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
    - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
    - ESTATUS: PARAM.ESTATUS
    - DOMICILIO: PARAM.DOMICILIO
    - INDICE: PARAM.INDICE
    - DESCUENTO: PARAM.DESCUENTO
    - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'SERVICIOS.ACTUALIZAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - CLIENTE: PARAM.CLIENTE
        - CUENTA: PARAM.CUENTA
        - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
        - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
        - ESTATUS: PARAM.ESTATUS
        - DOMICILIO: PARAM.DOMICILIO
        - INDICE: PARAM.INDICE
        - DESCUENTO: PARAM.DESCUENTO
        - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
- GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'SERVICIOS.ACTUALIZAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
        - CLIENTE: PARAM.CLIENTE
        - CUENTA: PARAM.CUENTA
        - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
        - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
        - ESTATUS: PARAM.ESTATUS
        - DOMICILIO: PARAM.DOMICILIO
        - INDICE: PARAM.INDICE
        - DESCUENTO: PARAM.DESCUENTO
        - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
    - HASH: e_HASH
- IF e_SER_UNIDAD != PARAM.ID_GLOBALNET_UNIDAD
    - e_FECHAHORA_CAMBIO_UNIDAD = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
        - ID_GLOBALNET_UNIDAD: SER_UNIDAD
        - DETALLES:
            - TIPO: 'SERVICIOS.ACTUALIZAR'
            - ID_GLOBALNET: PARAM.ID_GLOBALNET
            - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
            - CLIENTE: PARAM.CLIENTE
            - CUENTA: PARAM.CUENTA
            - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
            - ESTATUS: 'CANCELADO'
            - DOMICILIO: PARAM.DOMICILIO
            - INDICE: PARAM.INDICE
            - DESCUENTO: PARAM.DESCUENTO
            - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
        - FECHAHORA: e_FECHAHORA_CAMBIO_UNIDAD
        - ID_GLOBALNET_UNIDAD: e_SER_UNIDAD
        - DETALLES:
            - TIPO: 'SERVICIOS.ACTUALIZAR'
            - ID_GLOBALNET: PARAM.ID_GLOBALNET
            - FECHA_ULTIMA_MODIFICACION: PARAM.FECHA_ULTIMA_MODIFICACION
            - CLIENTE: PARAM.CLIENTE
            - CUENTA: PARAM.CUENTA
            - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - TIPO_SERVICIO: PARAM.TIPO_SERVICIO
            - FECHA_PROGRAMADO: PARAM.FECHA_PROGRAMADO
            - ESTATUS: 'CANCELADO'
            - DOMICILIO: PARAM.DOMICILIO
            - INDICE: PARAM.INDICE
            - DESCUENTO: PARAM.DESCUENTO
            - APLICA_DESCUENTO: PARAM.APLICA_DESCUENTO
        - HASH: e_HASH
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_SERVICIOS_FECHA (FECHAHORA)
    - FECHAHORA: PARAM.FECHA_ULTIMA_ACTUALIZACION

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHA_ULTIMA_MODIFICACION
    - CLIENTE
    - CUENTA
    - CUENTA_OCULTA
    - ID_GLOBALNET_UNIDAD
    - TIPO_SERVICIO
    - FECHA_PROGRAMADO
    - ESTATUS
    - DOMICILIO
    - INDICE
    - DESCUENTO
    - APLICA_CREDITO

### EN_PROCESO [POST]

#### Acciones

- e_HASH = md5("SERVICIOS.EN_PROCESO{PARAM.ID_GLOBALNET}{PARAM.FECHAHORA}{PARAM.ID_GLOBALNET_UNIDAD}")
- IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.EN_PROCESO (ID_GLOBALNET)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'SERVICIOS.EN_PROCESO'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
- GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'SERVICIOS.EN_PROCESO'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - HASH: e_HASH

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHAHORA
    - ID_GLOBALNET_UNIDAD

### CANCELAR [POST]

#### Acciones

- e_HASH = md5("SERVICIOS.CANCELAR{PARAM.ID_GLOBALNET}{PARAM.FECHAHORA}{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.RAZON_CANCELACION}")
- IF QUERY - SELECT COL_APL_ID FROM log_cola_globalnet WHERE COL_APL_HASH='HASH'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.CANCELAR (ID_GLOBALNET, RAZON_CANCELACION)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - RAZON_CANCELACION: PARAM.RAZON_CANCELACION
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
    - DETALLES:
        - TIPO: 'SERVICIOS.CANCELAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - RAZON_CANCELACION: PARAM.RAZON_CANCELACION
        - EMPLEADO: $GLOBALS['SYSTEM']['SECURITY']['EMPLEADO'].NUMERO
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - DETALLES:
        - TIPO: 'SERVICIOS.CANCELAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - RAZON_CANCELACION: PARAM.RAZON_CANCELACION
        - EMPLEADO: $GLOBALS['SYSTEM']['SECURITY']['EMPLEADO'].NUMERO
    - HASH: e_HASH

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - FECHAHORA
    - ID_GLOBALNET_UNIDAD
    - RAZON_CANCELACION

## OPE.CUENTAS_OCULTAS [/ope.cuentas_ocultas]

### AGREGAR [POST]

#### Acciones

- e_HASH = md5("CUENTAS_OCULTAS.AGREGAR{PARAM.ID_GLOBALNET}{PARAM.CUENTA_OCULTA}{PARAM.FECHAHORA}{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.ESTATUS}")
- IF QUERY - SELECT COL_APL_ID FROM log_cola_aplicacion WHERE COL_APL_HASH='HASH'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_CUENTAS_OCULTAS.AGREGAR (ID_GLOBALNET, CUENTA_OCULTA, FECHAHORA, ID_GLOBALNET_UNIDAD, ESTATUS)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET
    - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
    - FECHAHORA: PARAM.FECHAHORA
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - ESTATUS: PARAM.ESTATUS
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'CUENTAS_OCULTAS.AGREGAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
        - FECHAHORA: PARAM.FECHAHORA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - ESTATUS: PARAM.ESTATUS
- GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - DETALLES:
        - TIPO: 'CUENTAS_OCULTAS.AGREGAR'
        - ID_GLOBALNET: PARAM.ID_GLOBALNET
        - CUENTA_OCULTA: PARAM.CUENTA_OCULTA
        - FECHAHORA: PARAM.FECHAHORA
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - ESTATUS: PARAM.ESTATUS
    - HASH: e_HASH
- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_CUENTAS_OCULTAS_ID (ID_GLOBALNET)
    - ID_GLOBALNET: PARAM.ID_GLOBALNET

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET
    - CUENTA_OCULTA
    - FECHAHORA
    - ID_GLOBALNET_UNIDAD
    - ESTATUS

## OPE.LIQUIDACIONES [/ope.liquidaciones]

### ASIGNAR_INICIAL_ESTACIONARIO [POST]

#### Acciones

- e_HASH = md5("LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.FECHAHORA}{PARAM.MEDIDOR_INICIAL}{PARAM.ROTOGAUGE_INICIAL}")
- e_FECHA = substr(PARAM.FECHAHORA, 0, 10)
- IF QUERY - SELECT COL_APL_ID FROM log_cola_globalnet WHERE COL_APL_HASH='HASH'
    - RETURN
- IF NOT a_LIQUIDACION_ACTUAL = QUERY - SELECT LIQ_ID, LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='ABIERTA'
    - a_UNIDAD = QUERY - SELECT UNI_TIPO_UNIDAD, UNI_ID_RUTA, UNI_ID_CHOFER, UNI_ID_AYUDANTE, UNI_ID_AYUDANTE_2 FROM cat_unidades WHERE UNI_ID_GLOBALNET='PARAM.ID_GLOBALNET_UNIDAD'
    - IF a_LIQUIDACION_ANTERIOR = QUERY - SELECT LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='CERRADA' ORDER BY LIQ_VIAJE DESC
        - e_VIAJE = a_LIQUIDACION_ANTERIOR.VIAJE + 1
    - ELSE
        - e_VIAJE = 1
    - e_ID = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_LIQUIDACIONES.AGREGAR (ID_GLOBALNET_UNIDAD, VIAJE, FECHA, TIPO_UNIDAD, ID_RUTA, ID_CHOFER, ID_AYUDANTE, ID_AYUDANTE_2)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: e_VIAJE
        - FECHA: e_FECHA
        - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
        - ID_RUTA: a_UNIDAD.ID_RUTA
        - ID_CHOFER: a_UNIDAD.ID_CHOFER
        - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
        - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
    - e_FECHAHORA_AGREGAR = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
        - DETALLES:
            - TIPO: 'LIQUIDACIONES.AGREGAR'
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - VIAJE: e_VIAJE
            - FECHA: e_FECHA
            - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
            - ID_RUTA: a_UNIDAD.ID_RUTA
            - ID_CHOFER: a_UNIDAD.ID_CHOFER
            - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
            - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
        - FECHAHORA: e_FECHAHORA_AGREGAR
        - DETALLES:
            - TIPO: 'LIQUIDACIONES.AGREGAR'
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - VIAJE: e_VIAJE
            - FECHA: e_FECHA
            - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
            - ID_RUTA: a_UNIDAD.ID_RUTA
            - ID_CHOFER: a_UNIDAD.ID_CHOFER
            - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
            - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
        - HASH: e_HASH
- ELSE
    - e_ID = a_LIQUIDACION_ACTUAL.LIQ_ID
    - e_VIAJE = a_LIQUIDACION_ACTUAL.LIQ_VIAJE
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO (ID, MEDIDOR_INICIAL, ROTOGAUGE_INICIAL)
    - ID: e_ID
    - MEDIDOR_INICIAL: PARAM.MEDIDOR_INICIAL
    - ROTOGAUGE_INICIAL: PARAM.ROTOGAUGE_INICIAL
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
    - DETALLES:
        - TIPO: 'LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: e_VIAJE
        - FECHA: e_FECHA
        - MEDIDOR_INICIAL: PARAM.MEDIDOR_INICIAL
        - ROTOGAUGE_INICIAL: PARAM.ROTOGAUGE_INICIAL
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - DETALLES:
        - TIPO: 'LIQUIDACIONES.ASIGNAR_INICIAL_ESTACIONARIO'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: e_VIAJE
        - FECHA: e_FECHA
        - MEDIDOR_INICIAL: PARAM.MEDIDOR_INICIAL
        - ROTOGAUGE_INICIAL: PARAM.ROTOGAUGE_INICIAL
    - HASH: e_HASH

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA
    - MEDIDIOR_INICIAL
    - ROTOGAUGE_INICIAL

### ASIGNAR_FINAL_ESTACIONARIO [POST]

#### Acciones

- e_HASH = md5("LIQUIDACIONES.ASIGNAR_FINAL_ESTACIONARIO{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.FECHAHORA}{PARAM.MEDIDOR_FINAL}{PARAM.ROTOGAUGE_FINAL}")
- e_FECHA = substr(PARAM.FECHAHORA, 0, 10)
- IF QUERY - SELECT COL_APL_ID FROM log_cola_globalnet WHERE COL_APL_HASH='HASH'
    - RETURN
- IF NOT a_LIQUIDACION_ACTUAL = QUERY - SELECT LIQ_ID, LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='ABIERTA'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_LIQUIDACIONES.ASIGNAR_FINAL_ESTACIONARIO (ID, MEDIDOR_FINAL, ROTOGAUGE_FINAL)
    - ID: a_LIQUIDACION_ACTUAL.LIQ_ID
    - MEDIDOR_FINAL: PARAM.MEDIDOR_FINAL
    - ROTOGAUGE_FINAL: PARAM.ROTOGAUGE_FINAL
- FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
    - DETALLES:
        - TIPO: 'LIQUIDACIONES.ASIGNAR_FINAL_ESTACIONARIO'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: a_LIQUIDACION_ACTUAL.LIQ_VIAJE
        - FECHA: e_FECHA
        - MEDIDOR_FINAL: PARAM.MEDIDOR_FINAL
        - ROTOGAUGE_FINAL: PARAM.ROTOGAUGE_FINAL
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - DETALLES:
        - TIPO: 'LIQUIDACIONES.ASIGNAR_FINAL_ESTACIONARIO'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: a_LIQUIDACION_ACTUAL.LIQ_VIAJE
        - FECHA: e_FECHA
        - MEDIDOR_FINAL: PARAM.MEDIDOR_FINAL
        - ROTOGAUGE_FINAL: PARAM.ROTOGAUGE_FINAL
    - HASH: e_HASH

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA
    - MEDIDIOR_FINAL
    - ROTOGAUGE_FINAL

### VALIDAR_INICIAL_CILINDRO [POST]

#### Acciones

- e_HASH = md5("LIQUIDACIONES.VALIDAR_INICIAL_CILINDRO{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.FECHAHORA}")
- e_FECHA = substr(PARAM.FECHAHORA, 0, 10)
- IF QUERY - SELECT COL_APL_ID FROM log_cola_globalnet WHERE COL_APL_HASH='HASH'
    - RETURN
- IF NOT a_LIQUIDACION_ACTUAL = QUERY - SELECT LIQ_ID, LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='ABIERTA'
    - a_UNIDAD = QUERY - SELECT UNI_TIPO_UNIDAD, UNI_ID_RUTA, UNI_ID_CHOFER, UNI_ID_AYUDANTE, UNI_ID_AYUDANTE_2 FROM cat_unidades WHERE UNI_ID_GLOBALNET='PARAM.ID_GLOBALNET_UNIDAD'
    - IF a_LIQUIDACION_ANTERIOR = QUERY - SELECT LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='CERRADA' ORDER BY LIQ_VIAJE DESC
        - e_VIAJE = LIQUIDACION_ANTERIOR.VIAJE + 1
    - ELSE
        - e_VIAJE = 1
    - e_ID = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_LIQUIDACIONES.AGREGAR (ID_GLOBALNET_UNIDAD, VIAJE, FECHA, TIPO_UNIDAD, ID_RUTA, ID_CHOFER, ID_AYUDANTE, ID_AYUDANTE_2)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: e_VIAJE
        - FECHA: e_FECHA
        - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
        - ID_RUTA: a_UNIDAD.ID_RUTA
        - ID_CHOFER: a_UNIDAD.ID_CHOFER
        - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
        - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
    - FECHAHORA_AGREGAR = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
        - DETALLES:
            - TIPO: 'LIQUIDACIONES.AGREGAR'
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - VIAJE: e_VIAJE
            - FECHA: e_FECHA
            - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
            - ID_RUTA: a_UNIDAD.ID_RUTA
            - ID_CHOFER: a_UNIDAD.ID_CHOFER
            - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
            - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
        - FECHAHORA: e_FECHAHORA_AGREGAR
        - DETALLES:
            - TIPO: 'LIQUIDACIONES.AGREGAR'
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - VIAJE: e_VIAJE
            - FECHA: e_FECHA
            - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
            - ID_RUTA: a_UNIDAD.ID_RUTA
            - ID_CHOFER: a_UNIDAD.ID_CHOFER
            - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
            - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
        - HASH: e_HASH

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA

### VALIDAR_FINAL_CILINDRO [POST]

#### Acciones

- e_HASH = md5("LIQUIDACIONES.VALIDAR_FINAL_CILINDRO{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.FECHAHORA}")
- e_FECHA = substr(PARAM.FECHAHORA, 0, 10)
- IF QUERY - SELECT COL_APL_ID FROM log_cola_globalnet WHERE COL_APL_HASH='HASH'
    - RETURN
- IF NOT a_LIQUIDACION_ACTUAL = QUERY - SELECT LIQ_ID, LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='ABIERTA'
    - RETURN
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_LIQUIDACIONES.VALIDAR_FINAL_CILINDRO (ID)
    - ID: LIQUIDACION_ACTUAL.LIQ_ID
- FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
    - DETALLES:
        - TIPO: 'LIQUIDACIONES.VALIDAR_FINAL_CILINDRO'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: LIQUIDACION_ACTUAL.LIQ_VIAJE
        - FECHA: e_FECHA
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - DETALLES:
        - TIPO: 'LIQUIDACIONES.VALIDAR_FINAL_CILINDRO'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: LIQUIDACION_ACTUAL.LIQ_VIAJE
        - FECHA: e_FECHA
    - HASH: e_HASH

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA

## OPE.NOTAS [/ope.notas]

### AGREGAR [POST]

#### Acciones

- e_HASH = md5("NOTAS.AGREGAR{PARAM.ID_GLOBALNET_UNIDAD}{PARAM.FECHAHORA}{PARAM.CLIENTE}{PARAM.CUENTA}{PARAM.FOLIO}{PARAM.MONTO}{PARAM.TIPO_PAGO}{PARAM.DESCUENTO}{PARAM.LATITUD}{PARAM.LONGITUD}{PARAM.REFERENCIA}{PARAM.ID_GLOBALNET_SERVICIO}{PARAM.ID_GLOBALNET_CUENTA_OCULTA}")
- e_FECHA = substr(PARAM.FECHAHORA, 0, 10)
- IF QUERY - SELECT COL_APL_ID FROM log_cola_globalnet WHERE COL_APL_HASH='HASH'
    - RETURN
- IF NOT a_LIQUIDACION_ACTUAL = QUERY - SELECT LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='ABIERTA'
    - a_UNIDAD = QUERY - SELECT UNI_TIPO_UNIDAD, UNI_ID_RUTA, UNI_ID_CHOFER, UNI_ID_AYUDANTE, UNI_ID_AYUDANTE_2 FROM cat_unidades WHERE UNI_ID_GLOBALNET='PARAM.ID_GLOBALNET_UNIDAD'
    - IF a_LIQUIDACION_ANTERIOR = QUERY - SELECT LIQ_VIAJE FROM dat_liquidaciones WHERE LIQ_ID_GLOBALNET_UNIDAD='PARAM.ID_GLOBALNET_UNIDAD' AND LIQ_FECHA='e_FECHA' AND LIQ_ESTATUS='CERRADA' ORDER BY LIQ_VIAJE DESC
        - e_VIAJE = a_LIQUIDACION_ANTERIOR.VIAJE + 1
    - ELSE
        - e_VIAJE = 1
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_LIQUIDACIONES.AGREGAR (ID_GLOBALNET_UNIDAD, VIAJE, FECHA, TIPO_UNIDAD, ID_RUTA, ID_CHOFER, ID_AYUDANTE, ID_AYUDANTE_2)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: e_VIAJE
        - FECHA: e_FECHA
        - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
        - ID_RUTA: a_UNIDAD.ID_RUTA
        - ID_CHOFER: a_UNIDAD.ID_CHOFER
        - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
        - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
    - e_FECHAHORA_AGREGAR = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
        - DETALLES:
            - TIPO: 'LIQUIDACIONES.AGREGAR'
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - VIAJE: e_VIAJE
            - FECHA: e_FECHA
            - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
            - ID_RUTA: a_UNIDAD.ID_RUTA
            - ID_CHOFER: a_UNIDAD.ID_CHOFER
            - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
            - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
        - e_FECHAHORA: FECHAHORA_AGREGAR
        - DETALLES:
            - TIPO: 'LIQUIDACIONES.AGREGAR'
            - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
            - VIAJE: e_VIAJE
            - FECHA: e_FECHA
            - TIPO_UNIDAD: a_UNIDAD.TIPO_UNIDAD
            - ID_RUTA: a_UNIDAD.ID_RUTA
            - ID_CHOFER: a_UNIDAD.ID_CHOFER
            - ID_AYUDANTE: a_UNIDAD.ID_AYUDANTE
            - ID_AYUDANTE_2: a_UNIDAD.ID_AYUDANTE.2
        - HASH: e_HASH
- ELSE
    - e_VIAJE = a_LIQUIDACION_ACTUAL.LIQ_VIAJE
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_NOTAS.AGREGAR (ID_GLOBALNET_UNIDAD, VIAJE, FECHAHORA, CLIENTE, CUENTA, FOLIO, MONTO, TIPO_PAGO, DESCUENTO, LATITUD, LONGITUD, REFERENCIA)
    - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
    - VIAJE: e_VIAJE
    - FECHAHORA: PARAM.FECHAHORA
    - CLIENTE: PARAM.CLIENTE
    - CUENTA: PARAM.CUENTA
    - FOLIO: PARAM.FOLIO
    - MONTO: PARAM.MONTO
    - TIPO_PAGO: PARAM.TIPO_PAGO
    - DESCUENTO: PARAM.DESCUENTO
    - LATITUD: PARAM.LATITUD
    - LONGITUD: PARAM.LONGITUD
    - REFERENCIA: PARAM.REFERENCIA
- e_FECHAHORA = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (DETALLES)
    - DETALLES:
        - TIPO: 'NOTAS.AGREGAR'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: e_VIAJE
        - FECHA: e_FECHA
        - CUENTA: PARAM.CUENTA
        - TIPO_PAGO: PARAM.TIPO_PAGO
        - MONTO: PARAM.MONTO
        - FOLIO: PARAM.FOLIO
        - REFERENCIA: PARAM.REFERENCIA
- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.AGREGAR (FECHAHORA, DETALLES, HASH)
    - FECHAHORA: e_FECHAHORA
    - DETALLES:
        - TIPO: 'NOTAS.AGREGAR'
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - VIAJE: e_VIAJE
        - FECHA: e_FECHA
        - CUENTA: PARAM.CUENTA
        - TIPO_PAGO: PARAM.TIPO_PAGO
        - MONTO: PARAM.MONTO
        - FOLIO: PARAM.FOLIO
        - SERVICIO: PARAM.ID_GLOBALNET_SERVICIO ? PARAM.ID_GLOBALNET_SERVICIO : ''
        - CUENTA_OCULTA: PARAM.ID_GLOBALNET_CUENTA_OCULTA ? PARAM.ID_GLOBALNET_CUENTA_OCULTA : ''
        - REFERENCIA: PARAM.REFERENCIA
    - HASH: e_HASH
- IF PARAM.ID_GLOBALNET_SERVICIO
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_SERVICIOS.SURTIR (ID_GLOBALNET)
        - ID_GLOBALNET: PARAM.ID_GLOBALNET_SERVICIO
- IF PARAM.ID_GLOBALNET_CUENTA_OCULTA
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_CUENTAS_OCULTAS.OCUPADA (ID_GLOBALNET)
        - ID_GLOBALNET: PARAM.ID_GLOBALNET_CUENTA_OCULTA
    - e_FECHAHORA_CUENTA_OCULTA_APLICACION = GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.AGREGAR (ID_GLOBALNET_UNIDAD, DETALLES)
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - DETALLES:
            - TIPO: 'CUENTAS_OCULTAS.OCUPAR'
            - ID_GLOBALNET: PARAM.ID_GLOBALNET_CUENTA_OCULTA
    - GLOBAL_GAS.BE:C4.WRITE.DB.LOG_COLA_APLICACION.AGREGAR (FECHAHORA, ID_GLOBALNET_UNIDAD, DETALLES, HASH)
        - FECHAHORA: e_FECHAHORA_CUENTA_OCULTA_APLICACION
        - ID_GLOBALNET_UNIDAD: PARAM.ID_GLOBALNET_UNIDAD
        - DETALLES:
            - TIPO: 'CUENTAS_OCULTAS.OCUPAR'
            - ID_GLOBALNET: PARAM.ID_GLOBALNET_CUENTA_OCULTA
        - HASH: e_HASH

#### Retorno

- N/A

+ Attributes
    - ID_GLOBALNET_UNIDAD
    - FECHAHORA
    - CLIENTE
    - CUENTA
    - FOLIO
    - MONTO
    - TIPO_PAGO
    - DESCUENTO
    - LATITUD
    - LONGITUD
    - REFERENCIA
    - ID_GLOBALNET_SERVICIO
    - ID_GLOBALNET_CUENTA_OCULTA

## OPE.COLA_APLICACION [/ope.cola_aplicacion]

### DEPURAR [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_APLICACION.DEPURAR ()

#### Retorno

- N/A

## OPE.GLOBALNET [/ope.globalnet]

### CARGAR_SINCRONIZACION [POST]

#### Acciones

- TRY
    - GLOBAL_GAS.BE:C4.WRITE.WS.GLOBALNET.CARGAR_SINCRONIZACION (DETALLES)
        - DETALLES: PARAM.DETALLES
- CATCH
    - RETURN
- FOREACH PARAM.DETALLES AS m_ID => m_DETALLE
    - GLOBAL_GAS.BE:C4.WRITE.DB.DAT_COLA_GLOBALNET.ELIMINAR (ID)
        - ID: m_ID

#### Retorno

- N/A

+ Attributes
    - DETALLES

## OPE.SESION [/ope.sesion]

### INICIAR [POST]

#### Acciones

- e_JWT = GLOBAL_GAS.BE:C4.WRITE.DB.SEG_SESIONES.AGREGAR (ID_GLOBALNET_EMPLEADO)
    - ID_GLOBALNET_EMPLEADO: PARAM.ID_GLOBALNET_EMPLEADO

#### Retorno

- e_JWT

+ Attributes
    - ID_GLOBALNET_EMPLEADO

### DEPURAR [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.SEG_SESIONES.DEPURAR ()

#### Retorno

- N/A

## OPE.CONF_GENERAL [/ope.conf_general]

### ACTUALIZAR_SINCRONIZACION_GLOBALNET_FECHA_DESCARGA [POST]

#### Acciones

- GLOBAL_GAS.BE:C4.WRITE.DB.CONF_GENERAL.ACTUALIZAR_SINCRONIZACION_GLOBALNET_FECHA_DESCARGA (FECHAHORA)
    - FECHAHORA: PARAM.FECHAHORA

#### Retorno

- N/A

+ Attributes
    - FECHAHORA












